---

oracle_home: "{{ oracle_base }}/oracle/product/{{ oracle_version }}/{{ oracle_db_home }}"

oracle_user: { name: oracle, id: 5001, group: oinstall }

oracle_groups:   
    - { name: oinstall, id: 54321 }
    - { name: dba, id: 54322 } 
    - { name: asmoper, id: 54328 } 
    - { name: asmadmin, id: 54329 }
    - { name: asmdba, id: 54327 }

# shell environment for the oracle user
ora_user_env:
  ORACLE_BASE: "{{ oracle_base }}/oracle"
  ORACLE_SID: "{{ oracle_db_name }}"
  ORACLE_UNQNAME: "{{ oracle_db_name }}"
  ORACLE_HOME: "{{ oracle_home }}"
  NLS_LANG: "American_America.UTF8"