---
- block:
  - name: execute root.sh post-installation script
    command: "{{ oracle_grid_home }}/root.sh"
    register: root_script

  always:
  - name: save root script stdout
    copy:
      dest: "{{ oracle_tmp }}/root_script_grid.out"
      content: "{{ root_script.stdout | default('') }}"
    when: root_script.changed

  - name: save root script  stderr
    copy:
      dest: "{{ oracle_tmp }}/root_script_grid.err"
      content: "{{ root_script.stderr | default('') }}"
    when: root_script.changed

  ## Need to add a way to upload to a separate checklist_id for each node ##
  - name: Get files in a folder
    find:
      paths: "{{ oracle_grid_home }}/install/"
      patterns: "root_{{ ansible_hostname }}*.log"
    register: log_files
    tags:
    - apex_api

- name: upload logs for execute root script
  include_tasks: upload_log.yml
  vars:
    logfile_path: "{{ log_files.files | sort(attribute='mtime',reverse=true) | first | json_query('path') }}"
    log_file_desc: grid_root.sh
  tags:
    - apex_api

- name: db checklist status file upload for Upload root.sh log for grid
  import_role: oracle_api_services.yml
  tasks_from: db_checklist_status_file.yml
  vars:
    checklist_body:
      task_key: "{{ ansible_hostname }}"
      task_area: "GRID INSTALL"
      task_id: "{{ ticket_ref }}"
      task_status: "Upload Grid root.sh log"
      task_message: "Grid root.sh Log {{ ansible_hostname }}"
      file_mimetype: "text/plain"
      record_type: "file_upload"
      logfile_path: "{{ log_files.files | sort(attribute='mtime',reverse=true) | first | json_query('path') }}"
  tags:
  - apex_api
