---

- name: install grid
  environment: "{{ ora_user_env }}"
  shell: |
    su - {{ oracle_user }} -c "{{ oracle_tmp }}/grid/runInstaller -silent -force -ignorePrereq -ignoreSysPreReqs -responseFile {{ oracle_tmp }}/grid_install.rsp" 2>{{ oracle_tmp }}/grid_stderr.err >{{ oracle_tmp }}/grid_stdout.out &
    sleep 30
    while true
    do 
      c=$(ps -ef | grep -v grep | grep grid_install.rsp | grep java | wc -l)
      [ $c -eq 0 ] && break
      sleep 10
    done
  args:
    executable: /bin/bash
    creates: "{{ oracle_grid_home }}/cfgtoollogs/configToolAllCommands"
  when: inventory_hostname == master_node

- name: wait for orainstRoot.sh
  wait_for: 
    path: "{{ oracle_base }}/oraInventory/orainstRoot.sh"

- name: general oracle post-installation
  command: "{{ oracle_base }}/oraInventory/orainstRoot.sh"

- name: wait for root.sh
  wait_for: 
    path: "{{ oracle_grid_home }}/root.sh"

- name: db-specific oracle post-installation
  command: "{{ oracle_grid_home }}/root.sh"

- name: run grid configTool
  environment: "{{ ora_user_env }}"
  shell: |
    su - {{ oracle_user }} -c "{{ oracle_grid_home }}/cfgtoollogs/configToolAllCommands RESPONSE_FILE={{ oracle_tmp }}/grid_configTool.rsp" 2>{{ oracle_tmp }}/config_stderr.err >{{ oracle_tmp }}/config_stdout.out &
    sleep 30
    while true
    do 
      c=$(ps -ef | grep -v grep | grep grid_configTool.rsp | grep java | wc -l)
      [ $c -eq 0 ] && break
      sleep 10
    done
  args:
    executable: /bin/bash
  when: inventory_hostname == master_node