---

- name: install grid
  environment: "{{ ora_user_env }}"
  shell: |
    su - {{ oracle_user }} -c "{{ oracle_tmp }}/grid/runInstaller -silent -force -ignoreSysPreReqs -responseFile {{ oracle_tmp }}/grid_install.rsp" 2>{{ oracle_tmp }}/grid_stderr.err >{{ oracle_tmp }}/grid_stdout.out &
    sleep 30
    while true
    do 
      c=$(ps -ef | grep -v grep | grep grid_install.rsp | grep java | wc -l)
      [ $c -eq 0 ] && break
      sleep 10
    done
  args:
    executable: /bin/bash
    creates: "{{ oracle_grid_home }}/cfgtoollogs/configToolAllCommands"

# - name: get list of grid install fix scripts to run
#   register: grid_post_install_scripts


- name: run grid install fix scripts
  command: "{{ item }}"
  with_items: "{{ grid_post_install_scripts }}"

- name: run grid configTool
  environment: "{{ ora_user_env }}"
  shell: |
    su - {{ oracle_user }} -c "{{ oracle_grid_home }}/cfgtoollogs/configToolAllCommands RESPONSE_FILE={{ oracle_tmp }}/grid_configTool.rsp" 2>{{ oracle_tmp }}/config_stderr.err >{{ oracle_tmp }}/config_stdout.out &
    sleep 30
    while true
    do 
      c=$(ps -ef | grep -v grep | grep grid_configTool.rsp | grep java | wc -l)
      [ $c -eq 0 ] && break
      sleep 10
    done
  args:
    executable: /bin/bash