---

- include: copy_archives.yml

- name: get cvuqdisk package name
  find:
    paths: "{{ oracle_tmp }}/grid/rpm"
    file_type: file
    patterns: cvuqdisk*
    use_regex: yes
  register: cvuqdisk_package

- name: install cvuqdisk package
  yum: 
    name: "{{ cvuqdisk_package.files[0].path }}"
    state: present

## TODO: Need to get the 'hosts' variable for this to work
- name: run ssh setup
  command: "{{ oracle_tmp}}/grid/sshsetup/sshUserSetup.sh -user {{ oracle_user }} -hosts '{{ hosts }}' -advanced -exverify -confirm"
  when: grid_install_mode == CRS_CONFIG or grid_install_mode == CRS_SWONLY

- include: run_cluvfy.yml
  tags:
    - cluvfy
  when: inventory_hostname == master_node

- include: prep_rsp_file.yml
  when: inventory_hostname == master_node

- include: grid_install.yml
