---

- include: copy_archives.yml

- name: get cvuqdisk package name
  find:
    paths: "{{ oracle_tmp }}/grid/rpm"
    file_type: file
    patterns: cvuqdisk*
    use_regex: yes
  register: cvuqdisk_package

- name: install cvuqdisk package
  yum: 
    name: "{{ cvuqdisk_package.files[0].path }}"
    state: present

- name: ssh user equivalency
  block:
    - name: install expect if needed
      yum:
        name: expect
        state: present

    - name: copy in ssh_user_setup expect script
      template:
          src: ssh_user_setup.j2
          dest: "{{ oracle_tmp }}/ssh_user_setup.sh"
          mode: 0755

    - name: execute ssh_user_setup script
      command: "{{ oracle_tmp }}/ssh_user_setup.sh"
      
  when: inventory_hostname == master_node and (grid_install_mode == "CRS_CONFIG" or grid_install_mode == "CRS_SWONLY")

- include: run_cluvfy.yml
  tags:
    - cluvfy
  when: inventory_hostname == master_node

- name: get asm disk paths - {{ asm_disk_group }}
  find:
    paths: "{{ asm_disk_location }}"
    file_type: any
    patterns: "{{ asm_disk_group }}*"
    use_regex: no
  register: asm_disk_paths_find_result

- name: get asm disk paths - {{ asm_ocr_group }}
  find:
    paths: "{{ asm_disk_location }}"
    file_type: any
    patterns: "{{ asm_ocr_group }}*"
    use_regex: no
  register: asm_ocr_paths_find_result

- name: set cluster_nodes_table
  set_fact:
    cluster_nodes_table: "{{ cluster_nodes_table | default([]) }} + [ '{{ item }}:{{ item | regex_replace('([^.]*)(.*)','\\1-vip\\2')}}' ]"
  with_items: "{{ cluster_nodes }}"

- include_tasks: set_net_string.yml
  when: inventory_hostname == master_node and (grid_install_mode == "CRS_CONFIG" or grid_install_mode == "CRS_SWONLY")

- include: prep_rsp_file.yml
  when: inventory_hostname == master_node

- include: grid_install.yml
