---

- include: copy_archives.yml

- name: get cvuqdisk package name
  find:
    paths: "{{ oracle_tmp }}/grid/rpm"
    file_type: file
    patterns: cvuqdisk*
    use_regex: yes
  register: cvuqdisk_package

- name: install cvuqdisk package
  yum: 
    name: "{{ cvuqdisk_package.files[0].path }}"
    state: present

## TODO: Need to get the 'hosts' variable for this to work
- name: run ssh setup
  command: "{{ oracle_tmp}}/grid/sshsetup/sshUserSetup.sh -user {{ oracle_user }} -hosts '{{ hosts }}' -advanced -exverify -confirm"
  when: grid_install_mode == CRS_CONFIG or grid_install_mode == CRS_SWONLY

- include: run_cluvfy.yml
  tags:
    - cluvfy

- name: get asm disk paths
  find:
    paths: "{{ asm_disk_location }}"
    file_type: any
    patterns: "{{ asm_disk_group }}*"
    use_regex: no
  register: asm_disk_paths_find_result

- name: set asm_disk_paths
  set_fact:
    asm_disk_paths: "{{ asm_disk_paths_find_result | json_query('files[].path') | join(',')}}"

- include: prep_rsp_file.yml

- include: grid_install.yml
