---

- name: add create_ocr_disk.sql script
  template:
    src: create_ocr_disk.sql.j2
    dest: "{{ oracle_tmp }}/create_ocr_disk.sql"

- name: create OCR Disk in ASM
  become_user: '{{ oracle_user }}'
  environment: "{{ ora_user_env }}"
  command: sqlplus / as sysasm @{{ oracle_tmp }}/create_ocr_disk.sql

- name: add mount_asm_diskgroup.sql script
  template:
    src: mount_asm_diskgroup.sql.j2
    dest: "{{ oracle_tmp }}/mount_ocr_disk.sql"

- name: mount OCR disk in ASM
  become_user: '{{ oracle_user }}'
  environment: "{{ ora_user_env }}"
  command: sqlplus / as sysasm @{{ oracle_tmp }}/mount_ocr_disk.sql