---
 
- name: create grid_install rsp file (common)
  copy:
    dest: "{{ oracle_tmp }}/grid_install.rsp"
    content: |
       oracle.install.responseFileVersion=/oracle/install/rspfmt_crsinstall_response_schema_v12.1.0
       ORACLE_HOSTNAME={{ ansible_hostname }}.{{ domain }}
       INVENTORY_LOCATION={{ oracle_base }}/oraInventory
       SELECTED_LANGUAGES=en
       oracle.install.option={{ grid_install_mode }}
       ORACLE_BASE={{ oracle_base }}/oracle
       ORACLE_HOME={{ oracle_grid_home }}
       oracle.install.asm.OSDBA={{ oracle_group }}
       oracle.install.asm.OSOPER={{ oracle_group }}
       oracle.install.asm.OSASM={{ oracle_group }}
       oracle.install.crs.config.gpnp.scanName=
       oracle.install.crs.config.gpnp.scanPort=
       oracle.install.crs.config.ClusterType=
       oracle.install.crs.config.clusterName=
       oracle.install.crs.config.gpnp.configureGNS=
       oracle.install.crs.config.autoConfigureClusterNodeVIP=
       oracle.install.crs.config.gpnp.gnsOption=
       oracle.install.crs.config.gpnp.gnsClientDataFile=
       oracle.install.crs.config.gpnp.gnsSubDomain=
       oracle.install.crs.config.gpnp.gnsVIPAddress=
       oracle.install.crs.config.clusterNodes=
       oracle.install.crs.config.networkInterfaceList=
       oracle.install.crs.config.storageOption=
       oracle.install.crs.config.sharedFileSystemStorage.votingDiskLocations=
       oracle.install.crs.config.sharedFileSystemStorage.votingDiskRedundancy=
       oracle.install.crs.config.sharedFileSystemStorage.ocrLocations=
       oracle.install.crs.config.sharedFileSystemStorage.ocrRedundancy=
       oracle.install.crs.config.useIPMI=
       oracle.install.crs.config.ipmi.bmcUsername=
       oracle.install.crs.config.ipmi.bmcPassword=
       oracle.install.asm.SYSASMPassword={{ oracle_asm_syspass }}
       oracle.install.asm.diskGroup.name={{ asm_disk_group }}
       oracle.install.asm.diskGroup.redundancy=EXTERNAL
       oracle.install.asm.diskGroup.AUSize=1
       oracle.install.asm.diskGroup.disks={{ asm_disk_paths_find_result | json_query('files[].path') | join(',') }}
       oracle.install.asm.diskGroup.diskDiscoveryString={{ asm_disk_location }}/*
       oracle.install.asm.monitorPassword={{ oracle_asm_syspass }}
       oracle.install.asm.ClientDataFile=
       oracle.install.crs.config.ignoreDownNodes=false
       oracle.install.config.managementOption=NONE
       oracle.install.config.omsHost=
       oracle.install.config.omsPort=0
       oracle.install.config.emAdminUser=
       oracle.install.config.emAdminPassword=

- name: set inline changes for RAC
  lineinfile: 
    path: "{{ oracle_tmp }}/grid_install.rsp"
    regexp: "^{{ item.regex }}"
    line: "{{ item.regex }}={{ item.value }}"
  with_items:
    - { regex: oracle.install.crs.config.gpnp.scanName, value: "{{ cluster_name }}.{{ domain }}" }
    - { regex: oracle.install.crs.config.gpnp.scanPort, value: "{{ scan_port }}" }
    - { regex: oracle.install.crs.config.ClusterType, value: "{{ cluster_type }}" }
    - { regex: oracle.install.crs.config.clusterName, value: "{{ cluster_name }}" }
    - { regex: oracle.install.crs.config.gpnp.configureGNS, value: "false" }
    - { regex: oracle.install.crs.config.autoConfigureClusterNodeVIP, value: "true" }
    - { regex: oracle.install.crs.config.gpnp.gnsOption, value: "CREATE_NEW_GNS" }
    - { regex: oracle.install.crs.config.clusterNodes, value: "{{ cluster_nodes_table | join(',') }}" }
    - { regex: oracle.install.crs.config.networkInterfaceList, value: "{{ crs_net_interfaces | join(',') }}" }
    - { regex: oracle.install.crs.config.storageOption, value: "{{ grid_storage_type }}" }
    - { regex: oracle.install.crs.config.sharedFileSystemStorage.votingDiskLocations, value: "" }
    - { regex: oracle.install.crs.config.sharedFileSystemStorage.votingDiskRedundancy, value: "NORMAL" }
    - { regex: oracle.install.crs.config.sharedFileSystemStorage.ocrLocations, value: "{{ asm_ocr_paths_find_result | json_query('files[].path') | join(',') }}" }
    - { regex: oracle.install.crs.config.sharedFileSystemStorage.ocrRedundancy, value: "NORMAL" }
    - { regex: oracle.install.crs.config.useIPMI, value: "false" }
  when: grid_install_mode == "CRS_CONFIG" or grid_install_mode == "CRS_SWONLY"

- name: create configTool rsp file
  copy:
    dest: "{{ oracle_tmp }}/grid_configTool.rsp"
    content: |
      oracle.assistants.asm|S_ASMPASSWORD={{ oracle_asm_syspass }}
      oracle.assistants.asm|S_ASMMONITORPASSWORD={{ oracle_asm_syspass }}
      