---

- name: set cvu_config settings
  lineinfile: 
    path: "{{ oracle_tmp }}/cluster_verify/cv/admin/cvu_config"
    regexp: "^{{ item.regex }}"
    line: "{{ item.regex }}={{ item.value }}"
  with_items:
    - { regex: CV_RAW_CHECK_ENABLED, value: 'FALSE' }

- name: run cluvfy
  become: yes
  become_user: "{{ oracle_user }}"
  environment: "{{ ora_user_env }}"
  command: "{{ oracle_tmp }}/cluster_verify/bin/cluvfy stage -pre crsinst -n {{ ansible_hostname }} -fixup -verbose"
  ignore_errors: yes
  register: cluvfy_results_1

- name: save cluvfy 1st stdout
  copy:
    dest: "{{ oracle_tmp }}/cluvfy_1st_stdout.out"
    content: "{{ cluvfy_results_1.stdout }}"

- name: save cluvfy 1st stderr
  copy:
    dest: "{{ oracle_tmp }}/cluvfy_1st_stderr.err"
    content: "{{ cluvfy_results_1.stderr }}"

- name: Check for cluvfy failure
  command: echo RC=$?
  notify: 
  - run fixup script
  - re-run cluvfy
  when: cluvfy_results_1.rc != 0