host_details:
  - host_name: "DL_TEST_01"
    network_type: "BLUE"
    core_count: "{{ ansible_processor_cores | int }}"  # number
    processor_config_speed: ""
    server_model: ""
    hardware_vendor: "{{ ansible_system_vendor }}"
    os_type_version: "RHEL 6"
    processor_bit: "{{ ansible_userspace_bits | int }}"
    server_creation_date: ""  #date
    phy_virt: ""
    dc_location: "COLUMBUS"
    global_zone_solaris: ""
    phy_memory: ""  # number
    server_monitoring_tool: ""
    clustered: "N"
    os_type: ""
    env_source: ""
  - host_name: "dbtest05" 
    network_type: ""
    core_count: "{{ ansible_processor_cores | int }}"
    processor_config_speed: ""
    server_model: ""
    hardware_vendor: ""
    os_type_version: "{{ ansible_distribution_version }}"
    processor_bit: "{{ ansible_userspace_bits | int }}"
    server_creation_date: ""  #date
    phy_virt: ""
    dc_location: ""
    global_zone_solaris: ""
    phy_memory: ""  # number
    server_monitoring_tool: ""
    clustered: ""
    os_type: ""
    env_source: ""