---

# YML Structure For This File
# db_details:
#   - host_name: << host_name >>
#     databases:
#     - database_name: << database_name >>
#     - .......
#     - database_name: << database_name >>
#     - .......
#   - host_name: << host_name >>
#     databases:
#     - database_name: << database_name >>
#     - .......

## I didn't understand the purpose of this YAML and it was causing errors
## I have commented out and switched to a direct list of vars
# db_details: 
#   - host_name: "{{ ansible_hostname }}"
#     databases:
    # - database_name: "{{ oracle_db_name }}"
db_values:
  database_name: "{{ oracle_db_name }}"
  application_name: "{{ application_name }}"
  environment: "{{ db_environment }}"
  oracle_version: "{{ oracle_version }}"
  rac_type: "{% if rac_install == 'true' -%}RAC
              {%- else -%}STANDALONE
              {%- endif %}"
  business_unit: "{{ business_unit }}" 
  appliance: "{{ appliance }}"
  database_role: "{{ database_role }}" 
  pci_required: "{{ pci_required }}"
  sox_required: "{{ sox_required }}"
  encryption_required: "{{ encryption_required }}" 
  dataguard: "{{ dataguard }}"
  golden_gate: "{{ golden_gate }}"
  backup_enabled: "{{ backup_enabled }}" 
  end_of_life: "{{ end_of_life }}"
  db_monitoring_tool: "{{ db_monitoring_tool }}" 
  monitoring: "{{ monitoring }}"
  comments: "{{ comments }}"
  instance_count: "{{ instance_count }}"
  db_source: "{{ db_source }}"
  dr_solution: "{{ dr_solution }}"
  dr_location: "{{ dr_location }}"
  env_category: "{{ env_category }}"
  host_code: "{{ host_code }}"
  app_id: "{{ app_id }}"   
  storage_type: "{{ storage_type }}"
