host_inventory_insrt_body:
  host_name: "{{ ansible_hostname}}"
  network_type: "{{ network_type }}"
  core_count: "{{ ansible_processor_cores * ansible_processor_count }}"
  processor_config_speed: "{{ ansible_processor[2] | regex_replace('^.*@ (.*$)','\\1') }}"
  server_model: "{{ ansible_product_version }}"
  hardware_vendor: "{{ ansible_product_name | regex_replace('^([^ ]*).*','\\1') }}"
  os_type_version: "{{ ansible_distribution_version }}"
  processor_bit: "{{ processor_bit }}"
  phy_virt: "{{ phy_virt }}"
  dc_location: "{{ dc_location }}"
  global_zone_solaris: "{{ global_zone_solaris }}"
  phy_memory: "{{ ansible_memtotal_mb }}"
  server_monitoring_tool: "{{ server_monitoring_tool }}"
  host_code: "{{ host_code }}"
  clustered: "{{ clustered }}"
  os_type: "{{ os_type }}"
  env_source: "{{ env_source }}"