---

- name: Oracle Pre-Reqs
  hosts: '{{ host }}'
  become: yes
  become_method: sudo
  
  tasks:
  - name: run Charter pre-requirement checks
    import_role:
      name: oracle_prereqs
      tasks_from: Charter_checks