---

- name: install oracle 12c grid infrastructure
  hosts: '{{ host }}'
  become: yes
  become_method: sudo
  roles:
    - oracle_prereqs
    - oracle_asm_config
    - oracle_grid_infra_install
  vars:
    grid_version: 12.1.0.2
    grid_install_mode: HA_CONFIG
    domain: techlab.com
