---

- name: upgrade oracle 11g database to 12c database
  hosts: oracle
  become: yes
  become_method: sudo
  roles:
    - oracle_upgrade
  vars:
    oracle_version: 12.1.0.2
    db_home: db_2
    oracle_db_name: dummy
