---

- name: install oracle 12c grid infrastructure - RAC
  hosts: '{{ host }}'
  any_errors_fatal: true
  become: yes
  become_method: sudo
  tasks:
    - import_role:
        name: oracle_api_services
        tasks_from: cluster_member_insertion.yml
      vars:
        cluster_name: "{{ cluster_name | mandatory }}" ## must be passed in
        gi_version: "{{ grid_version }}"
        gi_current_patchset: ""
      tags:
      - apex_api

    - import_role:
        name: oracle_api_services
        tasks_from: host_inventory_insertion.yml
      vars:
        clustered: Y
      tags:
      - apex_api

    - import_role:
        name: oracle_api_services
        tasks_from: gi_checklist_insertion.yml
      tags:
      - apex_api

    - import_role:
        name: oracle_prereqs

    - import_role:
        name: oracle_grid_infra_install
  vars:
    grid_install_mode: CRS_CONFIG

  ## Required vars:
  # cluster_name - Name of the cluster

  ## Optional vars:
  # grid_version (default: 12.1.0.2)
  # env_source - Must be passed in or could be HostVar
  # network_type - Possibly HostVar?
  # global_zone_solaris - Possibly HostVar?
  # server_monitoring_tool - Possibly HostVar?
