---

- name: install oracle 12c grid infrastructure - RAC
  hosts: '{{ host }}'
  any_errors_fatal: true
  become: yes
  become_method: sudo
  tasks:
    - import_role:
        name: oracle_api_services
        tasks_from: cluster_member_insertion.yml
      vars:
        cluster_name: "{{ cluster_name | mandatory }}" ## must be passed in
        gi_version: "{{ grid_version }}"
        gi_current_patchset: ""
        env_source: "{{ env_source | mandatory }}" ## must be passed in

    - import_role:
        name: oracle_api_services
        tasks_from: host_inventory_insertion.yml
      vars:
        clustered: Y

    - import_role:
        name: oracle_api_services
        tasks_from: gi_checklist_insertion.yml

    - import_role:
        name: oracle_prereqs

    - import_role:
        name: oracle_asm_config
      when: ansible_distribution == "OracleLinux"

    - import_role:
        name: oracle_grid_infra_install
  vars:
    grid_version: 12.1.0.2
    grid_install_mode: CRS_CONFIG

  ## Input vars
  # env_source - OPTIONAL - Must be passed in or could be HostVar
  # network_type - OPTIONAL - Possibly HostVar?
  # global_zone_solaris - OPTIONAL - Possibly HostVar?
  # server_monitoring_tool - OPTIONAL - Possibly HostVar?
