---

- name: install oracle 12c grid infrastructure
  hosts: '{{ host }}'
  become: yes
  become_method: sudo
  tasks:
    - import_role:
        name: oracle_api_services
        tasks_from: host_inventory_insertion.yml
      vars:
        clustered: N
        env_source: "{{ env_source | mandatory }}"  ## must be passed in

    - import_role:
        name: oracle_api_services
        tasks_from: gi_checklist_insertion.yml

    - import_role:
        name: oracle_prereqs

    - import_role:
        name: oracle_asm_config
      when: ansible_distribution == "OracleLinux"

    - import_role:
        name: oracle_grid_infra_install

  vars:
    grid_version: 12.1.0.2
    grid_install_mode: HA_CONFIG
    