---

- name: install oracle 12c grid infrastructure
  hosts: '{{ host }}'
  become: yes
  become_method: sudo
  tasks:
    - import_role:
        name: oracle_prereqs

    - import_role:
        name: oracle_asm_config
      when: ansible_distribution == "OracleLinux"

    - import_role:
        name: oracle_grid_infra_install

  vars:
    grid_version: 12.1.0.2
    grid_install_mode: HA_CONFIG
    