---

- name: install oracle 12c grid infrastructure - RAC
  hosts: '{{ host }}'
  any_errors_fatal: true
  become: yes
  become_method: sudo
  roles:
    - oracle_prereqs
    - oracle_asm_config
    - oracle_grid_infra_install
  vars:
    grid_version: 12.1.0.2
    grid_install_mode: CRS_CONFIG
    domain: techlab.com
    cluster_name: scan2

    ##############################################
    ## Master Node will need these vars set ##
    ##############################################
    # public_net_interface - The iterface name that will be used for the public network
    # public_net_address - The IP address that will be used for the public network
    # private_net_interface - The iterface name that will be used for the private network
    # private_net_address - The IP address that will be used for the private network
