---

- name: test ssh keys
  hosts: '{{ host }}'
  become: yes
  become_method: sudo
  tasks:
    - import_role:
        name: oracle_grid_infra_install
        tasks_from: setup_ssh_user_equivalency.yml