---

oracle_version: 12.1.0.2

grid_version: 12.1.0.2

install_base: /u01/app

oracle_base: "{{ install_base }}/oracle"

# location for temporary files
oracle_tmp: /u01/tmp/postval/{{ oracle_db_name }}

oracle_db_home: db_1

oracle_home: "{{ oracle_base }}/product/{{ oracle_version }}/{{ oracle_db_home }}"

master_node: "{{ ansible_play_hosts | first }}"

oracle_installer_path: https://vm0pnyumxxw0001.twcable.com/yum/source/ORACLE_DB

pre_check_sqls:
  - pre_check_profile.sql
  - pre_check_default_profile.sql
  - pre_check_block_change.sql
  - pre_check_audit_purge.sql

#vars to be taken care
# ORACLE_SID