---
- name: Add TNSNAMES In RMAN 
  become: yes
  become_user: '{{ oracle_user }}'
  environment: "{{ ora_user_env }}"
  lineinfile:
    path: "{{ oracle_home }}/network/admin/tnsnames.ora"
    line: "{{ TARGET_DB }} = 
                (DESCRIPTION =
                (ADDRESS_LIST =
                (ADDRESS = (PROTOCOL = TCP)(HOST = {{ target_machine_name }})(PORT = 1521))
                )
                (CONNECT_DATA =
                (ORACLE_SID = {{ TARGET_DB_NAME }})
                )
                ) # line added by Ansible"

- name: Static Listener Configuration-Destination Server
  become: yes
  become_user: '{{ oracle_user }}'
  environment: "{{ ora_user_env }}"
  lineinfile:
    path: "{{ oracle_grid_home }}/network/admin/listener.ora"
    line: "SID_LIST_LISTENER =
                    (SID_LIST =
                      (SID_DESC =
                        (ORACLE_HOME = {{ oracle_home }})
                        (SID_NAME = {{ TARGET_DB_NAME }})
                      )
                    ) # line added by Ansible"
  when: inventory_hostname != master_node

- name: Reload the lister
  command: lsnrctl reload
  when: inventory_hostname != master_node

- name: Create a pfile-Source Server
  become: yes
  become_user: '{{ oracle_user }}'
  environment: "{{ ora_user_env }}"
  block:
  - name: Copy the create-pfile.sql file
    copy: 
      src: create-pfile.sql
      dest: "{{ oracle_tmp }}/create-pfile.sql"

  - name: Create spfile
    become: yes
    become_user: '{{ oracle_user }}'
    environment: "{{ ora_user_env }}"
    command: "sqlplus / as sysdba @{{ oracle_tmp }}/create-pfile.sql"
  when: inventory_hostname == master_node

- name: Copy pfile to target
  Shell: |
    scp -p {{ ORACLE_HOME }}/dbs/init{{ source_db_name }}.ora oracle@{{ target_db_server }}:{{ ORACLE_HOME }}/dbs
    scp -p {{ ORACLE_HOME }}/dbs/orapw{{ source_db_name}} oracle@{{ target_db_server }}:{{ ORACLE_HOME }}/dbs
  when: inventory_hostname == master_node

- name: create adump dir
  file:
    mode: 0755
    path: "{{ ORACLE_BASE }}/admin/orcl07/adump"
    state: directory

- name: Entry for the new database
  lineinfile:
    path: /etc/oratab
    line: '{{ target_db_name }}:{{ oracle_home }}:N   # line added by Ansible'
  
- name: REGISTER Database
  become: yes
  become_user: '{{ oracle_user }}'
  environment: "{{ ora_user_env }}"
  command: "rman target sys/{{ RMAN_password }}@{{ RMAN_DB }} auxiliary sys/{{ RMAN_password }}@{{ oracle_dup }}"
 