---
- import_role:
    name: oracle_api_services
    tasks_from: db_checklist_update.yml
  vars:
    chklst_json_body:
      new_entry: True
      checklist_type: "10"
      category_type: Install
      db_install_status: IN PROGRESS
  tags:
  - apex_api

- name: get oracle_sid
  shell: ps -ef | grep smon | grep {{ oracle_db_name }} | grep -v grep | awk '{ print $8 }'
  register: ps_grep_smon
  changed_when: False

- name: set oracle_sid
  set_fact:
    oracle_sid: "{{ ps_grep_smon.stdout | regex_replace('ora_smon_(.*)', '\\1') }}"

- name: get db details
  shell: grep "^{{ oracle_db_name }}:" /etc/oratab | awk 'NR == 1'
  ignore_errors: yes
  changed_when: false
  register: db_details

- name: set oracle_home
  set_fact:
    oracle_home: "{{ db_details.stdout | regex_replace('^[^:]*:([^:]*).*', '\\1') }}"

- fail:
    msg: Database named {{ oracle_db_name }} doesn't exists'
  when: oracle_home == ""

- name: complete block of post Provisioning validation
  block:
    - name: create tmp dir 
      file:
        group: "{{ oracle_group }}"
        owner: "{{ oracle_user }}"
        path: "{{ oracle_tmp }}"
        state: directory
        recurse: yes

    - name: create directories for post validation setup
      file:
        group: "{{ oracle_group }}"
        owner: "{{ oracle_user }}"
        path: "{{ directories }}"
        state: directory
        recurse: yes
      loop: "{{ create_directories }}"
      loop_control:
        loop_var: directories

    - name: check if untar check file exists
      stat:
        path: "{{ oracle_base }}/admin/untar_complete"
      register: untar_check

    - name: untar the tars
      unarchive:
        src: "{{ oracle_installer_path }}/{{ tars_file }}"
        dest: "{{ oracle_base }}/admin"
        remote_src: yes
        validate_certs: no
      when: untar_check.stat.exists == false
      loop:
        - scripts.tar
        - etc.tar
        - ctl.tar
      loop_control: 
        loop_var: tars_file

    - name: place a marker for completion
      file:
        path: "{{ oracle_base }}/admin/untar_complete"
        state: touch
      when: untar_check.stat.exists == false
    
    - include_tasks: cleanup_files_setup.yml

    - name: Set up Directory in ORACLE_ADMIN
      file:
        path: ‘{{ oracle_base }}/admin/chgctl’
        state: directory

    - name: Execute Post Provisioning
      include_tasks: "{{ filename }}"
      loop:
      - post_provisioning.yml
      - adrci_setup.yml
      loop_control:
        loop_var: filename
      when: master_node == inventory_hostname

    - include_tasks: oratab_entry.yml

    - import_role:
        name: oracle_api_services
        tasks_from: db_checklist_update.yml
      vars:
        chklst_json_body:
          new_entry: False
          db_install_status: SUCCESSFUL
      tags:
      - apex_api
  rescue:
    - import_role:
        name: oracle_api_services
        tasks_from: db_checklist_update.yml
      vars:
        chklst_json_body:
          new_entry: False
          db_install_status: Failed
      tags:
      - apex_api



