---

- name: create the oracle installer directory to the oracle user
  file:
    group: "{{ oracle_group }}"
    owner: "{{ oracle_user }}"
    path: "{{ oracle_tmp }}/database"
    state: directory
    recurse: yes

- name: check for the marker
  stat:
    path: "{{ oracle_tmp }}/database/copied"
  register: unzipped
  ignore_errors: yes

- name: get db installer zipfiles
  find:
    paths: "{{ oracle_installer_path }}/RDBMS/{{ oracle_version }}"
    file_type: file
    patterns: '*.zip'
  register: oracle_images

- name: unzip installer
  unarchive: 
    src: "{{ db_zipfile }}" 
    dest: "{{ oracle_tmp }}" 
    remote_src: yes 
    keep_newer: true
    validate_certs: no
  when: 
  - inventory_hostname == master_node
  - unzipped.stat.exists == false
  loop: "{{ oracle_images | json_query('files[].path') | sort }}"
  loop_control:
    loop_var: db_zipfile
  
- name: place a marker for the completion
  file:
    path: "{{ oracle_tmp }}/database/copied"
    state: touch
  when: unzipped.stat.exists == false