---

- block:
  - name: db-specific oracle post-installation
    command: "{{ oracle_home }}/root.sh"
    register: root_script

- always:
  - name: save root script stdout
    copy:
      dest: "{{ oracle_tmp }}/root_script_rdbms.out"
      content: "{{ root_script.stdout | default('') }}"
    when: root_script.changed

  - name: save root script  stderr
    copy:
      dest: "{{ oracle_tmp }}/root_script_rdbms.err"
      content: "{{ root_script.stderr | default('') }}"
    when: root_script.changed

  ## Need actual log location ##
  # - import_role:
  #     name: oracle_api_services
  #     tasks_from: upload_log.yml
  #   vars:
  #     logfile_path: "{{ oracle_base }}/path/to/log"
  #   tags:
  #   - apex_api