---

- include: copy_archives.yml

- name: create cluster_node_string
  set_fact:
    cluster_node_string: "{{ cluster_node_string | default([]) }} + [ '{{ hostvars[node_name]['ansible_hostname'] }}' ]"
  loop: "{{ cluster_nodes }}"
  loop_control:
    loop_var: node_name

- include: prep_rsp_file.yml
  when: inventory_hostname == master_node

- include: oracle.yml
