---

- name: install oracle
  environment: "{{ ora_user_env }}"
  shell: |
    su - {{ oracle_user }} -c "{{ oracle_tmp }}/database/runInstaller -silent -force -ignoreSysPreReqs -responseFile {{ oracle_tmp }}/db_install.rsp" 2>&1 | tee {{ oracle_tmp }}/db_stdout.out &
    sleep 30
    while true
    do 
      c=$(ps -ef | grep -v grep | grep db_install.rsp | grep java | wc -l)
      [ $c -eq 0 ] && break
      sleep 10
    done
  args:
    executable: /bin/bash
    creates: "{{ oracle_home }}/bin/sqlplus"
  register: db_install
  failed_when: '"[FATAL]" in db_install.stdout'
  when: inventory_hostname == master_node

- name: general oracle post-installation
  command: "{{ oracle_base }}/oraInventory/orainstRoot.sh"
  when: 'oracle_base + "/oraInventory/orainstRoot.sh" in hostvars[master_node]["db_install"]["stdout"]'

- name: execute root.sh script
  block:
  - name: db-specific oracle post-installation (Master)
    command: "{{ oracle_home }}/root.sh"
    when: inventory_hostname == master_node
    tags: root_script

  - name: db-specific oracle post-installation (Remaining)
    command: "{{ oracle_home }}/root.sh"
    when: inventory_hostname == item
    loop: "{{ cluster_nodes[1:] }}"
    tags: root_script
  when: 'oracle_home + "/root.sh" in hostvars[master_node]["db_install"]["stdout"]'
