---
oracle_version: 12.1.0.2

oracle_base: /u01/app/oracle

# oracle_db_home: grid

# location for temporary files
oracle_tmp: /u01/tmp/{{ oracle_version }}

oracle_user: oracle

oracle_grid_home: "/u01/app/12.1.0.2/grid"

oracle_home: "/u01/app/oracle/product/12.1.0.2/db_1"

#use the same db names for source and destination

Source_DB_NAME: db

TARGET_DB_NAME: db

# used in RMAN j2 file
db_name: db

# shell environment for the oracle user- Source Server
ora_user_env:
  ORACLE_BASE: "{{ oracle_base }}"
  ORACLE_SID: "{{ Source_DB_NAME }}"
  ORACLE_UNQNAME: "{{ Source_DB_NAME }}"
  ORACLE_HOME: "{{ oracle_home }}"
  NLS_LANG: "American_America.UTF8"
  PATH: "{{ oracle_home }}/bin:{{ ansible_env.PATH }}"

