---

install_base: /u01/app

oracle_base: "{{ install_base }}/oracle"

asm_disk_location: /dev/oracleasm/disks

asm_reco_group: RECO

exp_dg:
  name: EXP_DG
  dir: exp
  pattern: EXP*
  vol: EXP_FS_VOL
  size: 25

# Size in GB
exp_size: 25

oracle_version: 12.1.0.2

oracle_db_name: +ASM