---

oracle_version: 12.1.0.2

# Oracle Editions avaialble: EE, SEONE, SE
oracle_edition: EE

# location for temporary installation files
oracle_tmp: /u01/tmp/{{ oracle_version }}

install_base: /u01/app

oracle_base: "{{ install_base }}/oracle"

oracle_db_name: db


oracle_db_mem: "2048"

# FILE_SYSTEM_STORAGE | ASM_STORAGE
oracle_storage_type: ASM_STORAGE

asm_data_group: DATA

rac_install: "{% if ansible_play_hosts | length > 1 -%}true
              {%- else -%}false
              {%- endif %}"

oracle_installer_path: https://vm0pnyumxxw0001.twcable.com/yum/source/ORACLE_DB

oracle_image_map:
    - { image: "p13390677_112040_Linux-x86-64_1of7.zip", version: "11.2.0.4" }
    - { image: "p13390677_112040_Linux-x86-64_2of7.zip", version: "11.2.0.4" } 
    - { image: "linuxamd64_12102_database_1of2.zip", version: "12.1.0.2" }
    - { image: "linuxamd64_12102_database_2of2.zip", version: "12.1.0.2" } 

# Whether to start Oracle Enterprise Manager DBconsole
oracle_em: false

