---

- name: set disk label
  set_fact:
    disk_label: "{{ disk_info.path | basename | regex_replace('ora--dg--([^-]*).*', '\\1') | upper }}"

- name: create asm disk
  command: oracleasm createdisk {{ disk_label }} {{ disk_info.path }}
  args:
    creates: "{{ asm_disk_location }}/{{ disk_label }}"
  register: asm_create_result
  ignore_errors: yes

- name: chown asm disks
  block:
    - name: chown asm disks
      file:
        group: "{{ oracle_group }}"
        owner: "{{ oracle_user }}"
        path: "{{ asm_disk_location }}/{{ disk_label }}"
        state: file
  when: asm_create_result.rc != 0

- name: scan asm disks
  command: oracleasm scandisks

- name: confirm {{ disk_label }} is found
  command: oracleasm listdisks
  register: disk_confirm
  failed_when: 'disk_label not in disk_confirm.stdout_lines'