---

- name: set disk label
  set_fact:
    disk_label: "{{ disk_info.path | basename | regex_replace('ora--dg--([^-]*).*', '\\1') | upper }}"

- name: create asm disk
  command: oracleasm createdisk {{ disk_label }} {{ disk_info.path }}
  args:
    creates: "{{ asm_disk_location }}/{{ disk_label }}"
  ignore_errors: yes
  notify: chown the asm disk

- name: scan asm disks
  command: oracleasm scandisks

- name: confirm {{ disk_label }} is found
  command: oracleasm listdisks
  register: disk_confirm
  failed_when: 'disk_label not in disk_confirm.stdout_lines'