---

- name: install oracleasm tools
  yum: 
   name: oracleasm,oracleasm-support
   state: present

- name: configure oracleasm
  command: oracleasm configure -u {{ oracle_user }} -g {{ oracle_group }} -D {{ asm_disk_location}} -b -e

- name: initialize oracleasm
  command: oracleasm init
  ignore_errors: yes

- name: initialize asm_disk_paths
  set_fact:
    asm_disk_paths: []
    cacheable: true

- include_tasks: create_asm_disk.yml
  loop: "{{ asm_disks }}"
  loop_control:
    loop_var: disk_info

- name: Concatenate the asm_disk_paths
  set_fact:
    asm_disk_paths: "{{ asm_disk_paths | join(',') }}"