---
oracle_version: 12.1.0.2

oracle_base: /u01/app/oracle

# oracle_db_home: grid

# location for temporary files
oracle_tmp: /u01/tmp/{{ oracle_version }}

oracle_user: oracle

oracle_db_name: orcl07

# oracle_grid_home: "/u01/app/12.1.0.2/grid"

oracle_home: "/u01/app/oracle/product/12.1.0.2/db_db_1"

# shell environment for the oracle user
ora_user_env:
  ORACLE_BASE: "{{ oracle_base }}"
  ORACLE_SID: "{{ oracle_db_name }}"
  ORACLE_UNQNAME: "{{ oracle_db_name }}"
  ORACLE_HOME: "{{ oracle_home }}"
  NLS_LANG: "American_America.UTF8"
  PATH: "{{ oracle_home }}/bin:{{ ansible_env.PATH }}"



directory_name: 

path_to_directory:

export_filename:

logfile_name:

#table_exists_action=<SKIP|REPLACE|APPEND>

table_exists_action: 