---
oracle_version: 12.1.0.2

oracle_base: /u01/app/oracle

oracle_db_home: db_1

# location for temporary files
oracle_tmp: /u01/tmp/{{ oracle_version }}

oracle_user: oracle

oracle_db_name: demo11

oracle_home: "{{ oracle_base }}/product/{{ oracle_version }}/{{ oracle_db_home }}"

# shell environment for the oracle user
ora_user_env:
  ORACLE_BASE: "{{ oracle_base }}"
  ORACLE_SID: "{{ oracle_db_name }}"
  ORACLE_UNQNAME: "{{ oracle_db_name }}"
  ORACLE_HOME: "{{ oracle_home }}"
  NLS_LANG: "American_America.UTF8"
  PATH: "{{ oracle_home }}/bin:{{ ansible_env.PATH }}"

oracle_db_ServiceName: db_test_RMAN

TNSNAMES: dbtest07.techlab.com

