---
  
install_base: /u01/app

oracle_base: "{{ install_base }}/oracle"

oracle_tmp: /u01/tmp/{{ oracle_version }}

oracle_version: 12.1.0.2

oracle_grid_version: 12.1.0.2

grid_home: "/u01/app/{{ oracle_grid_version }}/grid"

rdbms_name: "{{ rdbms_name | mandatory }}"

uninstallation_type: "{{ uninstallation_type | mandatory  }}" # if set to standalone 

database_name: "{% if uninstallation_type == 'cluster' %} {{ database_name | mandatory }} 
                {% else %} 
                {% endif %}"

