---

- include_vars: var_cluster_member_insertion.yml

- name: check if cluster Member name exists
  shell:  cat /root/api_service/ansible_db_details.txt | grep -e '^ID Of cluster*'
  register: is_cl_name_exist
  ignore_errors: yes

- name: Complete Tasks Of Cluster Member Insertion
  block:
    - name: Insert Starting Part of the Cluster Name For Identification
      lineinfile: 
        path: /root/api_service/ansible_db_details.txt
        line: "ID Of cluster"
      when: is_cl_name_exist.stdout == ""

    - name: Make A POST Call To Insert Cluster Member Details In V_CLUSTER_MEMBER_TBL
      uri:
        url: https://apex.techlab.com:8443/ords/invent2/charter/insertclustermember
        validate_certs: no  # should be removed after https certs becomes renewed
        method: POST
        body_format: json
        body: "{{ cluster_membr_body }}"
        headers:
            Content-Type: "application/json"
      register: v_cluster_membr_detail_insertion_response
    
    - name: Check Whether HOST_CODE Exist or Not
      shell: cat /root/api_service/ansible_db_details.txt | grep -e '^V_HOST_CODE'
      register: is_host_code_exist
      ignore_errors: yes

    - name: Get The HOST_CODE From Response
      lineinfile:
        path: /root/api_service/ansible_db_details.txt
        line: "V_HOST_CODE of {{ ansible_hostname }} is={{ v_cluster_membr_detail_insertion_response.json | json_query('HOST_CODE') }}"
      when: is_host_code_exist.rc == 1
      
    - name: Insert The cluster_name_id In ansible_db_details.txt File
      lineinfile:
        path: /root/api_service/ansible_db_details.txt
        regexp: "^ID Of cluster"
        line: "ID Of cluster={{ v_cluster_membr_detail_insertion_response.json | json_query('ID') }}"

  rescue:
     - name: Remove the ID String Since POST call Didn't Succeed
       lineinfile:
        path: /root/api_service/ansible_db_details.txt
        regexp: "^ID Of cluster*"
        state: absent

  when: is_cl_name_exist.rc == 1