- name: generate json_body
  set_fact: 
    chklst_json_body: '{{ chklst_json_body | default({}) | combine({ item.key: item.value }) }}'
  with_items: "{{ update_cluster_cklist_body }}"

- name: get host checklist ID
  shell: cat /root/api_service/ansible_db_details.txt | grep -e '^ID Of checklist for cluster*' | awk -F '=' '{print $2}'
  register: cluster_cklst_id

- name: update the json data using PUT call
  uri:
    url:  "{{ apex_url }}/db_check_list/{{ cluster_cklst_id.stdout }}"
    validate_certs: no  # should be removed after https certs becomes renewed
    method: PUT
    body_format: json
    body: "{{ chklst_json_body }}"
    headers:
        Content-Type: "application/json"
    when: cluster_cklst_id.stdout != ""