---

- name: Create A File For Inserting ID Details Formed In DB
  lineinfile: 
    path: /root/api_service/ansible_db_details.txt
    line: DETAILS OF THE ID'S WE GET AFTER POST CALLS
    create: yes

- include_vars: var_cluster_member_insertion.yml

- name: check if cluster Member name exists
  shell:  cat /root/api_service/ansible_db_details.txt | grep -e '^ID Of cluster*'
  register: is_cl_name_exist
  ignore_errors: yes

- name: Complete Tasks Of Cluster Member Insertion
  block:
    - name: Insert Starting Part of the Cluster Name For Identification
      lineinfile: 
        path: /root/api_service/ansible_db_details.txt
        line: "ID Of cluster"
        create: yes
      when: is_cl_name_exist.stdout == ""

    - name: Make A POST Call To Insert Cluster Member Details In V_CLUSTER_MEMBER_TBL
      uri:
        url: "{{ apex_url }}/insertclustermember"
        validate_certs: no  # should be removed after https certs becomes renewed
        method: POST
        body_format: json
        body: "{{ cluster_membr_body }}"
        headers:
            Content-Type: "application/json"
      register: v_cluster_membr_detail_insertion_response
      when: inventory_hostname == master_node

    - name: save results to all nodes
      set_fact:
        v_cluster_membr_detail_insertion_response: "{{ hostvars[master_node].v_cluster_membr_detail_insertion_response }}"
    
    - name: Check Whether HOST_CODE Exist or Not
      shell: cat /root/api_service/ansible_db_details.txt | grep -e '^V_HOST_CODE'
      register: is_host_code_exist
      ignore_errors: yes

    - name: Get The HOST_CODE From Response
      lineinfile:
        path: /root/api_service/ansible_db_details.txt
        line: "V_HOST_CODE of {{ ansible_hostname }} is={{ v_cluster_membr_detail_insertion_response.json | json_query('HOST_CODE') }}"
      when: is_host_code_exist.rc == 1
      
    - name: Insert The cluster_name_id In ansible_db_details.txt File
      lineinfile:
        path: /root/api_service/ansible_db_details.txt
        regexp: "^ID Of cluster"
        line: "ID Of cluster={{ v_cluster_membr_detail_insertion_response.json | json_query('ID') }}"

  rescue:
    - name: Remove the ID String Since POST call Didn't Succeed
      lineinfile:
        path: /root/api_service/ansible_db_details.txt
        regexp: "^ID Of cluster*"
        state: absent

    - name: Store the Json If APEX Server Is Down
      block:
        - name: Put The Json In A File
          lineinfile:
            path: /root/api_service/unsent_json_body/cluster_membr_body.json
            line: "{{ cluster_membr_body }}"
            create: yes
        - name: Make Single Quotes to Double Quotes
          shell: sed -i 's|'\''|\"|g' /root/api_service/unsent_json_body/cluster_membr_body.json 
      when: v_cluster_membr_detail_insertion_response.status == "500"
  when: is_cl_name_exist.rc == 1