---

- name: insert new checklist entry
  include_tasks: cluster_checklist_insertion.yml
  when: chklst_json_body.new_entry

- name: Checklist Update
  block:
  - name: update the json data using PUT call
    uri:
      url:  "{{ apex_url }}/charter_check_list/db_check_list/{{ checklist_id }}"
      validate_certs: no  # should be removed after https certs becomes renewed
      method: PUT
      body_format: json
      body: "{{ chklst_json_body }}"
      register: checklist_update_response
      headers:
          Content-Type: "application/json"

  rescue:
  - name: Store the Json If APEX Server Is Down
    delegate_to: localhost
    become: no
    lineinfile:
      path: "{{ json_backup_dir }}/{{ cluster_name }}_cluster_chklst_updates.json"
      line: '{
                "cluster_name": "{{ cluster_name }}",
                "checklist_id": "{{ checklist_id }}",
                "update": {{ chklst_json_body | to_json }} 
              }'
      create: yes