---

- include_vars: var_cluster_member_insertion.yml

- import_role:
    name: oracle_api_services
    tasks_from: get_cluster_id.yml
  when: cluster_id is not defined

- name: Complete Tasks Of Cluster Member Insertion
  block:
    - name: Make A POST Call To Insert Cluster Member Details In V_CLUSTER_MEMBER_TBL
      uri:
        url: "{{ apex_url }}/insertclustermember"
        validate_certs: no  # should be removed after https certs becomes renewed
        method: POST
        body_format: json
        body: "{{ cluster_membr_body }}"
        headers:
            Content-Type: "application/json"
      register: v_cluster_membr_detail_insertion_response
      when: inventory_hostname == master_node

    - name: Get The HOST_CODE From Response
      set_fact:
        host_code: "{{ hostvars[master_node].v_cluster_membr_detail_insertion_response.json | json_query('HOST_CODE') }}"
      
  rescue:
    - name: Store the Json If APEX Server Is Down
      block:
        - name: Put The Json In A File
          lineinfile:
            path: "{{ json_backup_dir }}/cluster_membr_body.json"
            line: "{{ cluster_membr_body }}"
            create: yes
        - name: Make Single Quotes to Double Quotes
          shell: sed -i 's|'\''|\"|g' /root/api_service/unsent_json_body/cluster_membr_body.json 
      when: v_cluster_membr_detail_insertion_response.status == "500"
  when: cluster_id == ""

- import_tasks: host_inventory_insertion.yml
  vars:
    clustered: Y