---

- import_role:
    name: oracle_api_services
    tasks_from: get_db_id.yml
  when: db_id is not defined

- name: Complete Tasks Of DB Checklist Insertion
  block:
    - name: Make A POST Call To Insert DB Checklist Details In V_DB_CHECK_LIST
      uri:
        url: "{{ apex_url }}/insert_db_check_list"
        validate_certs: no  # should be removed after https certs becomes renewed
        method: POST
        body_format: json
        body: {
            "db_id": "{{ db_id }}"
            }
        status_code: 200,201
        headers:
            Content-Type: "application/json"
      register: db_checklist_insrt_response
      
    - name: Insert The Id Of DB Checklist In ansible_db_details.txt File
      set_fact:
        checklist_id: "{{ db_checklist_insrt_response.json | json_query('ID') }}"

  rescue:
    - name: Store the Json If APEX Server Is Down
      lineinfile:
        path: /root/api_service/unsent_json_body/db_chklst_insertion_body.json
        line: '{"db_id" : "{{ db_id }}"}'
        create: yes
      when: db_checklist_insrt_response.status == "500"