---
- name: get Db ID line
  command: grep -e '^ID Of {{ oracle_db_name }} database' /root/api_service/ansible_db_details.txt
  register: db_line

- name: set db_id
  set_fact:
    db_id: "{{ db_line.stdout  | regex_replace('.*=(.*)','\\1')}}"
    
- name: check if db checklist name exists
  shell:  cat /root/api_service/ansible_db_details.txt | grep -e '^ID Of checklist for {{ oracle_db_name }} db*'
  register: is_db_chklst_name_exist
  ignore_errors: yes

- name: Complete Tasks Of DB Checklist Insertion
  block:
    - name: Insert Starting Part of the db checklist Name For Identification
      lineinfile: 
        path: /root/api_service/ansible_db_details.txt
        line: "ID Of checklist for {{ oracle_db_name }} db"
      when: is_db_chklst_name_exist.stdout == ""

    - name: Make A POST Call To Insert DB Checklist Details In V_DB_CHECK_LIST
      uri:
        url: https://apex.techlab.com:8443/ords/invent2/charter/insert_db_check_list
        validate_certs: no  # should be removed after https certs becomes renewed
        method: POST
        body_format: json
        body: {
            "db_id": "{{ db_id }}"
            }
        headers:
            Content-Type: "application/json"
      register: db_checklist_insrt_response
      
    - name: Insert The Id Of DB Checklist In ansible_db_details.txt File
      lineinfile:
        path: /root/api_service/ansible_db_details.txt
        regexp: "^ID Of checklist for {{ oracle_db_name }} db*"
        line: "ID Of checklist for {{ oracle_db_name }} db={{ db_checklist_insrt_response.json | json_query('ID') }}"

  rescue:
    - name: Remove the ID String Since POST call Didn't Succeed
      lineinfile:
        path: /root/api_service/ansible_db_details.txt
        regexp: "^ID Of checklist for {{ oracle_db_name }} db*"
        state: absent
  when: is_db_chklst_name_exist.rc == 1