- include_vars: var_db_checklist_insertion.yml

- name: get Db ID 
  shell: echo "{{ db_name_and_id }}" | awk -F " " '{ print $1 }'
  register: dbid

- name: get Db Name
  shell: echo "{{ db_name_and_id }}" | awk -F " " '{ print $2 }'
  register: dbname

- name: set db name and Id
  set_fact:
    dbid: "{{ dbid.stdout }}"
    dbname: "{{ dbname.stdout }}"
   
- name: check if db checklist name exists
  shell:  cat /root/api_service/ansible_db_details.txt | grep -e '^ID Of checklist for {{ dbname }} db*'
  register: is_db_chklst_name_exist
  ignore_errors: yes

- name: get host_id
  shell: cat /root/api_service/ansible_db_details.txt | grep -e '^ID Of {{ ansible_hostname }}*' | awk -F '=' '{print $2}'
  register: host_id

- name: Complete Tasks Of DB Checklist Insertion
  block: 
    - name: Insert Starting Part of the db checklist Name For Identification
      lineinfile: 
        path: /root/api_service/ansible_db_details.txt
        line: "ID Of checklist for {{ dbname }} db"
      when: is_db_chklst_name_exist.stdout == ""

    - name: Make A POST Call To Insert DB Checklist Details In V_DB_CHECK_LIST
      uri:
        url: https://apex.techlab.com:8443/ords/invent2/charter/insert_db_check_list
        validate_certs: no  # should be removed after https certs becomes renewed
        method: POST
        body_format: json
        body: {
            "host_id": "{{ host_id.stdout }}",
            "checklist_type": "{{ checklist_details.checklist_type }}", 
            "post_build_status": "{{ checklist_details.post_build_status }}", 
            "cluster_verify": "{{ checklist_details.cluster_verify }}", 
            "gi_install_status": "{{ checklist_details.gi_install_status }}", 
            "db_install_status": "{{ checklist_details.db_install_status }}",
            "db_upgrade_status": "{{ checklist_details.db_upgrade_status }}",
            "gi_upgrade_status": "{{ checklist_details.gi_upgrade_status }}", 
            "migration_status": "{{ checklist_details.migration_status }}", 
            "post_migration_status": "{{ checklist_details.post_migration_status }}", 
            "execution_id": "{{ checklist_details.execution_id }}",
            "db_id": "{{ dbid }}"
            }
        headers:
            Content-Type: "application/json"
      register: db_checklist_insrt_response
      
    - name: Insert The Id Of DB Checklist In ansible_db_details.txt File
      lineinfile:
        path: /root/api_service/ansible_db_details.txt
        regexp: "^ID Of checklist for {{ dbname }} db*"
        line: "ID Of checklist for {{ dbname }} db={{ db_checklist_insrt_response.json | json_query('ID') }}"
  when: is_db_chklst_name_exist.rc == 1

  rescue:
    - name: Remove the ID String Since POST call Didn't Succeed
      lineinfile:
        path: /root/api_service/ansible_db_details.txt
        regexp: "^ID Of checklist for {{ dbname }} db*"
        state: absent