
---

- include_vars: var_db_inventory_insertion.yml

- name: check if db inventory name exists
  shell:  cat /root/api_service/ansible_db_details.txt | grep -e '^ID Of {{ db_invntry_insrtion_body.database_name }}'
  register: is_db_inv_name_exist
  ignore_errors: yes


- name: Complete Tasks Of DB Inventory Insertion
  block:
    - name: Insert Starting Part of the Host Inventory Name For Identification
      lineinfile: 
        path: /root/api_service/ansible_db_details.txt
        line: "ID Of {{ db_invntry_insrtion_body.database_name }}"
      when: is_db_inv_name_exist.stdout == ""

  #  "app_id" is a fk and needs to discussed and is not in body of post call
    - name: Make A POST Call To Insert DB Inventory Details In V_DB_INVENTORY
      uri:
        url: "{{ apex_url }}/insert_db_inventory"
        validate_certs: no  # should be removed after https certs becomes renewed
        method: POST
        body_format: json
        body: "{{ db_invntry_insrtion_body }}"
        headers:
            Content-Type: "application/json"
      register: v_db_inventory_insertion_response

    - name: Insert The db_member_id In ansible_db_details.txt File
      lineinfile:
        path: /root/api_service/ansible_db_details.txt
        regexp: "^ID Of {{ db_invntry_insrtion_body.database_name }}*"
        line: "ID Of {{ db_invntry_insrtion_body.database_name }} database={{ v_db_inventory_insertion_response.json | json_query('ID') }}"
  rescue:
     - name: Remove the ID String Since POST call Didn't Succeed
       lineinfile:
        path: /root/api_service/ansible_db_details.txt
        regexp: "^ID Of {{ db_invntry_insrtion_body.database_name }}*"
        state: absent
     - name: Store the Json If APEX Server Is Down
       block:
        - name: Put The Json In A File
          lineinfile:
            path: /root/api_service/unsent_json_body/db_invtry_insrtion_body.json
            line: "{{ db_invntry_insrtion_body }}"
            create: yes
        - name: Make Single Quotes to Double Quotes
          shell: sed -i 's|'\''|\"|g' /root/api_service/unsent_json_body/db_invtry_insrtion_body.json 
       when: v_db_inventory_insertion_response.status == "500"   
  when: is_db_inv_name_exist.rc == 1

