
---

- import_role:
    name: oracle_api_services
    tasks_from: get_host_code.yml
  when: host_code is not defined

- import_role:
    name: oracle_api_services
    tasks_from: get_db_id.yml
  vars:
    oracle_db_name: "{{ oracle_db_name }}"

- include_vars: var_db_inventory_insertion.yml

- name: Complete Tasks Of DB Inventory Insertion
  block:
  #  "app_id" is a fk and needs to discussed and is not in body of post call
    - name: Make A POST Call To Insert DB Inventory Details In V_DB_INVENTORY
      uri:
        url: "{{ apex_url }}/insert_db_inventory"
        validate_certs: no  # should be removed after https certs becomes renewed
        method: POST
        body_format: json
        body: "{{ db_invntry_insrtion_body }}"
        headers:
            Content-Type: "application/json"
      register: v_db_inventory_insertion_response

  rescue:
     - name: Store the Json If APEX Server Is Down
       block:
        - name: Put The Json In A File
          lineinfile:
            path: "{{ json_backup_dir }}/db_invtry_insrtion_body.json"
            line: "{{ db_invntry_insrtion_body }}"
            create: yes
        - name: Make Single Quotes to Double Quotes
          shell: sed -i 's|'\''|\"|g' /root/api_service/unsent_json_body/db_invtry_insrtion_body.json 
       when: v_db_inventory_insertion_response.status == "500"   
  when: db_id == ""

