---

- block:
  - name: GET cluster_id from APEX
    uri:
      url: "{{ apex_url }}/get_cluster_id/{{ cluster_name | urlencode }}"
      validate_certs: no  # should be removed after https certs becomes renewed
      method: GET
    register: cluster_id_get_response

  - name: set cluster_id
    set_fact:
      cluster_id: "{{ cluster_id_get_response.json | json_query('id') }}"
  
  rescue:
  - name: set cluster_id
    set_fact:
      cluster_id: ""