---

- name: GET host_id from APEX
  uri:
    url: "{{ apex_url }}/get_host_id/{{ ansible_hostname }}"
    validate_certs: no  # should be removed after https certs becomes renewed
    method: GET
  ignore_errors: yes
  register: host_id_get_response

- name: name debug host_id
  debug:
    var: host_id_get_response
    
- name: set host_id
  set_fact:
    host_id: "{{ host_id_get_response.json.items.id }}"
    #host_id: "{{ host_id_get_response.json | default('{`items`:[{`id`:``}]}') | json_query('items[0].id') }}"