---

- block:
  - name: GET host_code from APEX
    uri:
      url: "{{ apex_url }}/get_host_code/{{ ansible_hostname }}"
      validate_certs: no  # should be removed after https certs becomes renewed
      method: GET
    register: host_code_get_response

  - name: set host_code
    set_fact:
      host_code: "{{ host_code_get_response.json | json_query('items[0].host_code') }}"
    when: host_code_get_response.json | json_query('items[0].host_code') != ""
  
  rescue:
  - name: set host_code
    set_fact:
      host_code: ""