- name: Create A File For Inserting ID Details Formed In DB
  lineinfile: 
    path: /root/api_service/ansible_db_details.txt
    line: DETAILS OF THE ID'S WE GET AFTER POST CALLS
    create: yes
    
- include_vars: var_host_inventory_insertion.yml

- name: check if host inventory name exists
  shell:  cat /root/api_service/ansible_db_details.txt | grep -e '^ID Of {{ ansible_hostname }}*'
  register: is_host_inv_name_exist
  ignore_errors: yes

- name: Complete Tasks Of Host Inventory Insertion
  block: 
    - name: Insert Starting Part of the Host Inventory Name For Identification
      lineinfile: 
        path: /root/api_service/ansible_db_details.txt
        line: "ID Of {{ ansible_hostname }}"
      when: is_host_inv_name_exist.stdout == ""

    - name: Make a POST call to insert host details in V_HOST_INV_TBL
      uri:
        url: https://apex.techlab.com:8443/ords/invent2/charter/insert_host_inventory
        validate_certs: no  # should be removed after https certs becomes renewed
        method: POST
        body_format: json
        body: "{{ host_inventory_insrt_body }}"
        headers:
            Content-Type: "application/json"
      register: v_host_detail_insertion_response

    - name: Insert The v_host_inventory_id In ansible_db_details.txt File
      lineinfile:
        path: /root/api_service/ansible_db_details.txt
        regexp: "^ID Of {{ ansible_hostname }}*"
        line: "ID Of {{ ansible_hostname }}={{ v_host_detail_insertion_response.json | json_query('ID') }}"

    - name: Insert The V_HOST_CODE In ansible_db_details.txt File
      lineinfile:
        path: /root/api_service/ansible_db_details.txt
        line: "V_HOST_CODE of {{ ansible_hostname }}={{ host_code }}"

  rescue:
    - name: remove entry for failed host
      lineinfile:
        path: /root/api_service/ansible_db_details.txt
        regexp: "^ID Of {{ ansible_hostname }}*"
        state: absent

  when: is_host_inv_name_exist.rc == 1


