- include_vars: var_host_inventory_insertion.yml

- name: Make A Variable
  set_fact:
    host_inv_json_body: "{"

- name: Form a Json
  set_fact: 
    host_inv_json_body: '{{ host_inv_json_body | string }} "{{ item.key }}": "{{ item.value }}"{{ item.delimiter }}'
  with_items: "{{ update_host_inv_body }}"

- name: End the Variable
  set_fact:
    host_inv_json_body: '{{ host_inv_json_body | string }} }'

- name: get id
  shell: cat /root/api_service/ansible_db_details.txt | grep -e '^ID Of {{ ansible_hostname }}' | awk -F '=' '{print $2}'
  register: host_inv_id

- name: update the json data
  uri:
    url: https://apex.techlab.com:8443/ords/invent2/charter/host_inventory/{{ host_inv_id.stdout }}
    validate_certs: no  # should be removed after https certs becomes renewed
    method: PUT
    body_format: json
    body: "{{ host_inv_json_body }}"
    headers:
      Content-Type: "application/json"
  when: host_inv_id.stdout != ""