- name: check if host checklist name exists
  shell:  cat /root/api_service/ansible_db_details.txt | grep -e '^ID Of checklist for {{ ansible_hostname }}*'
  register: is_host_chklst_name_exist
  ignore_errors: yes

- name: Complete Task Of Host CheckList Insertion
  block: 
    - name: Insert Starting Part of the db checklist Name For Identification
      lineinfile: 
        path: /root/api_service/ansible_db_details.txt
        line: "ID Of checklist for {{ ansible_hostname }}"
      when: is_host_chklst_name_exist.stdout == ""

    - name: Get The HOST ID
      shell: cat /root/api_service/ansible_db_details.txt | grep -e '^ID Of {{ ansible_hostname }}*' | awk -F '=' '{ print $2 }'
      register: host_id

    - name: Make A POST Call To Insert HOST Checklist Details In V_DB_CHECK_LIST
      uri:
        url: https://apex.techlab.com:8443/ords/invent2/charter/insert_db_check_list
        validate_certs: no  # should be removed after https certs becomes renewed
        method: POST
        body_format: json
        body: {
            "host_id": "{{ host_id.stdout }}"
            }
        headers:
            Content-Type: "application/json"
      register: host_checklist_insrt_response

    - name: Insert The Id Of Host Checklist In ansible_db_details.txt File
      lineinfile:
        path: /root/api_service/ansible_db_details.txt
        regexp: "^ID Of checklist for {{ ansible_hostname }}*"
        line: "ID Of checklist for {{ ansible_hostname }}={{ host_checklist_insrt_response.json | json_query('ID') }}"
  rescue:
    - name: Remove the ID String Since POST call Didn't Succeed
      lineinfile:
        path: /root/api_service/ansible_db_details.txt
        regexp: "^ID Of checklist for {{ ansible_hostname }}*"
        state: absent
  when: is_host_chklst_name_exist.rc == 1