---

- name: check if oracle has already been installed
  command: grep -q "^{{ oracle_db_name }}:" /etc/oratab
  ignore_errors: yes
  register: oracle_installed
  failed_when: oracle_installed.rc == 0
  when: install_mode == "INSTALL_DB_AND_CONFIG"

- include: copy_archives.yml

- name: create cluster_node_string
  set_fact:
    cluster_node_string: "{{ cluster_node_string | default([]) }} + [ '{{ node_name | regex_replace('([^\\.]*).*','\\1') }}' ]"
  loop: "{{ cluster_nodes }}"
  loop_control:
    loop_var: node_name
  when: rac_install == true

- include: prep_rsp_file.yml
  when: inventory_hostname == master_node

- include: oracle.yml
