---

- name: check if oracle has already been installed
  command: grep -q "^{{ oracle_db_name }}:" /etc/oratab
  ignore_errors: yes
  register: oracle_installed
  failed_when: oracle_installed.rc == 0

# We may go this route instead of using the 'prep_rsp_file' play
#- name: compose the oracle automated installer settings
#  template:
#    src: db_install.rsp.{{ oracle_version | regex_replace ('^([0-9]{1,2}.[0-9]{1,}.[0-9]{1,})(.*)$','\g<1>') }}.j2
#    dest: "{{ oracle_tmp }}/db_install.rsp"
#    owner: "{{ oracle_user[0].name }}"
#    group: "{{ oracle_group[0].name }}"

- include: copy_archives.yml

- include: prep_rsp_file.yml

- include: oracle.yml
