---

- include_role:
    name: oracle_api_services
    tasks_from: application_details_insertion.yml

- name: get App ID
  command: grep 'ID Of {{ application_name }}' /root/api_service/ansible_db_details.txt
  register: app_id_line

- name: set app_id
  set_fact:
    app_id: "{{ app_id_line.stdout | regex_replace('^.*=([0-9]*)','\\1') }}"

- name: get Host ID
  command: grep 'V_HOST_CODE of {{ ansible_hostname }}' /root/api_service/ansible_db_details.txt
  register: host_id_line

- name: set host_code
  set_fact:
    host_code: "{{ host_id_line.stdout | regex_replace('^.*=(.*)','\\1') }}"

- include_role:
    name: oracle_api_services
    tasks_from: db_inventory_insertion.yml