---


# - name: Get oracle Database Home
#   shell: "awk -F : 'NF > 1 {print $2}' /etc/oratab |grep -v grid|grep {{ oracle_version }}" 
#   changed_when: False
#   register: ora_home_list
#   ignore_errors: True
- include_tasks: get_db_home.yml

- include_tasks: process_ojvm_patch.yml
  when: ora_home_list | length == 0