---

- name: get db details
  command: grep "^{{ oracle_db_name }}:" /etc/oratab
  register: db_details

- name: set original_oracle_home
  set_fact:
    current_oracle_home: "{{ db_details.stdout | regex_replace('^[^:]*:([^:]*).*', '\\1') }}"

- name: ensure 12c is installed
  stat:
    path: "{{ oracle_home }}/bin/dbua"
  register: ora_12c_installed

- name: install 12c sw_only if needed
  include_role: 
    name: oracle_install
  when: ora_12c_installed.stat.exists == false

- import_tasks: upgrade_prechecks.yml

- name: check for precheck failures
  fail:
    msg: There were {{ precheck_results_count.errors }} errors in the Precheck script
  when: precheck_results_count.errors | int > 0

- name: ensure dbs dir in new home
  file:
    path: "{{ new_oracle_home }}/dbs"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    state: directory
    mode: 755
  
- name: move ora and orapw files
  shell: cp -p {{ current_oracle_home }}/dbs/{{ curr_file }} {{ new_oracle_home }}/dbs/
  args:
    creates: '{{ new_oracle_home }}/dbs/{{ curr_file }}'
  loop:
  - init.ora
  - init{{ oracle_db_name }}*.ora
  - orapw{{ oracle_db_name }}*
  loop_control:
    loop_var: curr_file
  
- include: upgrade_oracle.yml
  when: 
    - db_details.rc == 0
    - current_oracle_home | regex_replace('.*/product/([^/]*).*', '\\1') != oracle_version

- import_tasks: upgrade_postchecks.yml
