---

- name: upgrade oracle
  become: yes
  become_user: "{{ oracle_user }}"
  environment: "{{ ora_user_env }}"
  shell: |
    dbua -silent -sid {{ oracle_db_name }} -oracleHome {{ current_oracle_home }} -sysDBAUserName sys -sysDBAPassword {{ oracle_db_syspass }} -recompile_invalid_objects true -degree_of_parallelism 4 2>{{ oracle_tmp }}/db_upgrade_stderr.err >{{ oracle_tmp }}/db_upgrade_stdout.out &
    sleep 30
    while true
    do 
      c=$(ps -ef | grep dbua | grep {{ oracle_db_name }} | grep java | wc -l)
      [ $c -eq 0 ] && break
      sleep 10
    done
  args:
    executable: /bin/bash
    creates: "{{ oracle_home }}/bin/sqlplus"