---

- name: Run datapatch
  become: yes
  become_user: "{{ oracle_user }}"
  environment: "{{ ora_user_env }}"
  command: datapatch -verbose
  register: datapatch

- name: save datapatch stdout
  copy:
    dest: "{{ oracle_tmp }}/datapatch.out"
    content: "{{ datapatch.stdout }}"
  changed_when: False

- name: save datapatch stderr
  copy:
    dest: "{{ oracle_tmp }}/datapatch.err"
    content: "{{ datapatch.stderr }}"
  changed_when: False
  when: datapatch.stderr_lines | length > 0