---

- name: backup existing opatch
  command: mv {{ oracle_home }}/OPatch {{ oracle_home }}/OPatch.old
  args:
    removes: "{{ oracle_home }}/OPatch"

- name: install updated opatch ({{ opatch_version_required }})
  ignore_errors: yes
  unarchive:
    src: "{{ oracle_installer_path }}/OPATCH/{{ opatch_util_installer }}"
    dest: "{{ oracle_home }}"
    remote_src: yes
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    mode: 0755
    validate_certs: no

- import_tasks: check_opatch.yml

- name: Failure Block
  block:
  - name: restore opatch from backup
    command: mv {{ oracle_home }}/OPatch.old {{ oracle_home }}/OPatch

  - fail:
      msg: opatch not installed
  when: opatch_version != opatch_version_required