---

- name: backup existing opatch
  command: mv {{ oracle_home }}/OPatch {{ oracle_home }}/OPatch.old
  args:
    removes: "{{ oracle_home }}/OPatch"
    
- name: host checklist post for Patching
  include_tasks: db_patch_checklist_post_update.yml
  vars:
    chklst_json_body:
      ID: "{{ checklist_id }}"
      patch_status: Installing OPatch
      new_entry: False
  tags:
  - apex_api
- name: install updated opatch ({{ opatch_version_required }})
  ignore_errors: yes
  unarchive:
    src: "{{ oracle_installer_path }}/OPATCH/{{ opatch_util_installer }}"
    dest: "{{ oracle_home }}"
    remote_src: yes
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    mode: 0755
    validate_certs: no

- import_tasks: check_opatch.yml

- name: host checklist post for Patching
  include_tasks: db_patch_checklist_post_update.yml
  vars:
    chklst_json_body:
      patch_status: Installed OPatch
      new_entry: False
  when: opatch_version == opatch_version_required
  tags:
  - apex_api

- name: Failure Block
  block:
  - name: restore opatch from backup
    command: mv {{ oracle_home }}/OPatch.old {{ oracle_home }}/OPatch
  - name: host checklist post for Grid Install
    include_task: db_checklist_post_update.yml
    vars:
      chklst_json_body:
        new_entry: False
        ID: "{{ checklist_id }}"
        checklist_type: PATCH
        category_type: Install
        db_install_status: OPATCH Install FAILED
    when: fresh_install
    tags:
    - apex_api

- name: host checklist post for Patching
  include_tasks: db_patch_checklist_post_update.yml
  vars:
      chklst_json_body:
        patch_status: OPATCH install FAILED
        new_entry: False
  tags:
    - apex_api
- fail:
      msg: opatch not installed
  when: opatch_version != opatch_version_required