---

- name: create tmp dir
  file:
    group: "{{ oracle_group }}"
    owner: "{{ oracle_user }}"
    path: "{{ oracle_tmp }}"
    state: directory
    recurse: yes

- include_tasks: copy_archives.yml

- include_tasks: opatch_prereq.yml

- include_tasks: opatch_apply.yml
  when: inventory_hostname == curr_node
  loop: "{{ ansible_play_hosts }}"
  loop_control:
    loop_var: curr_node

- include_tasks: opatch_inventory.yml

- name: Run datapatch
  become: yes
  become_user: "{{ oracle_user }}"
  environment: "{{ ora_user_env }}"
  command: $OPATCHDIR/datapatch -verbose
  register: datapatch
  when: patch_type == 'ORACLE'