---

- import_role:
    name: oracle_api_services
    tasks_from: db_patch_checklist_update.yml
  vars:
    chklst_json_body:
      patch_status: 'RUNNING OPATCH APPLY'
      new_entry: False
  tags:
  - apex_api
- name: Run Opatch
  environment: "{{ ora_user_env }}"
  command: opatchauto apply {{ pstage }}/{{ patch_num }} {{ opatch_flags }} -oh {{ oracle_home }}
  register: opatch_apply

- name: save opatch apply stdout
  copy:
    dest: "{{ oracle_tmp }}/opatch_apply.out"
    content: "{{ opatch_apply.stdout }}"
  changed_when: False

- name: save opatch prereq stderr
  copy:
    dest: "{{ oracle_tmp }}/opatch_apply.err"
    content: "{{ opatch_apply.stderr }}"
  changed_when: False
  when: opatch_apply.stderr_lines | length > 0

- name: get opatch logfile
  find:
    paths: "{{ oracle_home }}/cfgtoollogs/opatch"
    file_type: file
    age: -10m
    age_stamp: mtime
    patterns: opatch\d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2}[AP]M.log
    use_regex: yes
  register: opatch_log
  when: inventory_hostname == master_node
  tags:
  - apex_api

- name: Get latest log file
  set_fact:
    latest_file: "{{ opatch_log.files | sort(attribute='mtime',reverse=true) | first }}"
    
- import_role:
    name: oracle_api_services
    tasks_from: db_patch_upload_log.yml
  vars:
    logfile_path:   "{{ opatch_log.files[0].path }}"
  when: 
  - inventory_hostname == master_node
  - opatch_log.files[0] is defined
  tags:
  - apex_api

