---

- name: execute rootdeinstall.sh
  command: "{{ script_path }}/rootdeinstall.sh"
  ignore_errors: yes
  failed_when: "'successfully deconfigured' not in rootdeinstall_script.stdout"
  register: rootdeinstall_script

- name: save rootdeinstall_script stdout
  copy:
    dest: "{{ oracle_tmp }}/rootdeinstall_script.out"
    content: "{{ rootdeinstall_script.stdout }}"

- name: save rootdeinstall_script stderr
  copy:
    dest: "{{ oracle_tmp }}/rootdeinstall_script.err"
    content: "{{ rootdeinstall_script.stderr }}" 