---

- name: get db details
  command: grep ":{{ oracle_home }}:" /etc/oratab
  register: db_details
  changed_when: False

- name: create db_list
  set_fact:
    db_list: "{{ db_list | default([]) }} + [ '{{ item | regex_replace('^([^:]*).*','\\1') }}' ]"
  loop: "{{ db_details.stdout_lines }}"

- name: create {{ deinstall_product }}_deinstall.rsp file
  template:
    owner: "{{ oracle_user }}"
    src: "{{ deinstall_product }}_deinstall.rsp.j2"
    dest: "{{ oracle_tmp }}/{{ deinstall_product }}_deinstall.rsp"
  when: inventory_hostname == master_node

##########################################################
## We may need to find a way to add the following lines ##
## for each DB in the given DB Home                     ##
##########################################################
# FAST_RECOVERY_LOC.{{ db }}={{ oracle_base }}/fast_recovery_area/ORCL
# ARCHIVE_LOG_DESTINATION_LOC.{{ db }}=
# DUMP_DESTINATION_LOC.{{ db }}={{ oracle_base }}/admin/{{ db }}
# LOCAL_SID.{{ db }}={{ db }}
# RAW_MAPPING_FILE.{{ db }}=
# SID_LIST.{{ db }}={{ db }}
# DATAFILE_LOC.{{ db }}={{ oracle_base }}/oradata/{{ db }},{{ oracle_base }}/fast_recovery_area/{{ db }}
# CREATION_MODE.{{ db }}=y
# CONFIGFILE_LOC.{{ db }}=
# SPFILE_LOC.{{ db }}={{ oracle_base }}/product/12.1.0/dbhome_1/dbs/spfile{{ db }}.ora
# DBCA_LOG.{{ db }}={{ oracle_base }}/cfgtoollogs/dbca/{{ db }}
# DIAG_DEST.{{ db }}={{ oracle_base }}/diag/rdbms/{{ db }}
# EMCA_LOG.{{ db }}={{ oracle_base }}/cfgtoollogs/emca/{{ db }}