---

oracle_home: "{{ oracle_base }}/product/{{ oracle_version }}/{{ oracle_db_home }}"

oracle_user: oracle

oracle_group: oinstall

# shell environment for the oracle user
ora_user_env:
  ORACLE_BASE: "{{ oracle_base }}"
  ORACLE_SID: "{{ oracle_db_name }}"
  ORACLE_UNQNAME: "{{ oracle_db_name }}"
  ORACLE_HOME: "{{ oracle_home }}"
  NLS_LANG: "American_America.UTF8"
  PATH: "{{ ansible_env.PATH }}:{{ oracle_home }}/bin"