---

oracle_compat_version: "{{ grid_version | regex_replace('^([0-9]{1,2}.[0-9]{1,}).*','\\1') }}"

oracle_grid_home: "{{ oracle_grid_home }}"

oracle_home: "{{ oracle_base }}/oracle/product/{{ grid_version }}/{{ oracle_db_home }}"

oracle_sid: "{% if checklist_task == 'cluster' -%}{{ oracle_db_name }}1
             {%- else -%}{{ oracle_db_name }}
             {%- endif %}"

oracle_user: oracle

oracle_group: oinstall

oracle_dba_group: dba

# shell environment for the oracle user
ora_user_env:
  ORACLE_BASE: "{{ oracle_base }}/oracle"
  ORACLE_SID: "{{ oracle_sid }}"
  ORACLE_UNQNAME: "{{ oracle_db_name }}"
  ORACLE_HOME: "{{ oracle_grid_home }}"
  NLS_LANG: "American_America.UTF8"
  PATH: "{{ oracle_grid_home }}/bin:{{ ansible_env.PATH }}"
  TMP: "/u01/app/oracle"
  TMPDIR: "/u01/app/oracle"

checklist_task: "{% if ansible_play_hosts | length == 1 -%}host
                 {%- elif ansible_play_hosts | length > 1 -%}cluster
                 {%- endif %}"

cluster_nodes: "{{ ansible_play_hosts }}"

master_node: "{{ ansible_play_hosts | first }}"

## This is the using a Default that can be maintained in Tower as a Group Var
grid_image_query: "[?version == `{{ grid_version }}`].image"
grid_images: "{{ grid_image_map | json_query(grid_image_query) }}"

## You can also use the following instead and store the list of files in
## the GRID/<version> folder on the Yum Server
# grid_images: "{{ lookup('url', oracle_installer_path + '/image_details.txt', validate_certs=no, wantlist=True) }}"