---

# shell environment for the oracle user
ora_user_env:
  ORACLE_BASE: "{{ oracle_base }}/oracle"
  ORACLE_SID: "{{ oracle_db_name }}"
  ORACLE_UNQNAME: "{{ oracle_db_name }}"
  ORACLE_HOME: "{{ oracle_home }}"
  NLS_LANG: "American_America.UTF8"

known_cluvfy_issues: 
  - "Swap Size"
  - "Package: cvuqdisk"
  - "Multicast check"
  - "source"
  - "NTP"
  - "Domain Sockets"