---

- name: Update PowerShell
  hosts: "{{ host }}"
  become: yes
  become_user: Administrator
  become_method: runas
  vars:
    ansible_become_pass: VMware1!
  tasks:

  - name: Update PowerShell (WMF)
    win_chocolatey:
      name: powershell
      state: present
      version: '5.1.14409.20180105'
    register: ps_update

  - name: reboot to finish PowerShell Update
    win_reboot:
      pre_reboot_delay: 5
      test_command: whoami
      reboot_timeout: 600
      msg: Reboot initiated by Ansible
      connect_timeout: 5
    when: ps_update.changed == True