---

- name: create tmp dir
  file:
    group: "{{ oracle_group }}"
    owner: "{{ oracle_user }}"
    path: "{{ oracle_tmp }}"
    state: directory
    recurse: yes

- import_tasks: reco_disks.yml
  vars: 
    diskgroup_name: "{{ asm_reco_group }}"

- import_tasks: exp_disks.yml
  vars:
    diskgroup_name: "{{ asm_exp_group }}"