---

- name: create "exp" directory
  file:
    group: "{{ oracle_group }}"
    owner: "{{ oracle_user }}"
    path: ‘{{ oracle_base }}/exp’
    state: directory

- name: add create_exp_disk.sql script
  template:
    src: create_exp_disk.sql.j2
    dest: "{{ oracle_tmp }}/create_exp_disk.sql"

- name: create ACFS Disk in ASM
  become_user: '{{ oracle_user }}'
  environment: "{{ ora_user_env }}"
  command: sqlplus / as sysasm @{{ oracle_tmp }}/create_exp_disk.sql

- name: As oracle (on primary node if RAC)
  block:
      - name: creating "acfs" file system
        become: yes
        become_user: '{{ oracle_user }}'
        environment: "{{ ora_user_env }}"
        command: |
          /sbin/mkfs -t acfs /dev/oracleasm/disks/EXP003
          /sbin/mkfs -t acfs /dev/asm/exp_fs_vol-5
        # filesystem:
        #   fstype: acfs
        #   dev: /dev/asm/exp_fs_vol-5
      - name: Mount the disk
        command: '/bin/mount -t acfs /dev/asm/exp_fs_vol-5 {{ oracle_base }}/exp'
        # mount:
        #   path: /u01/app/oracle/exp
        #   src: /dev/asm/exp_fs_vol-5
        #   fstype: acfs
        #   state: present
  when: inventory_hostname == master_node

- name: Mount on additional nodes (if any)
  block:
  - name: add mount_exp_disk.sql script
    copy:
      src: mount_exp_disk.sql
      dest: "{{ oracle_tmp }}/mount_exp_disk.sql"

  - name: mount ACFS disk in ASM
    become_user: '{{ oracle_user }}'
    environment: "{{ ora_user_env }}"
    command: sqlplus / as sysasm @{{ oracle_tmp }}/mount_exp_disk.sql

  - name: creating "acfs" file system
    become_user: '{{ oracle_user }}'
    environment: "{{ ora_user_env }}"
    command: '/sbin/mkfs -t acfs /dev/asm/exp_fs_vol-5'

  - name: Mount the disk
    command: '/bin/mount -t acfs /dev/asm/exp_fs_vol-5 {{ oracle_base }}/exp'
  when:
  - rac_install == true
  - inventory_hostname != master_node

