---

- name: add lines in ifcfg-enp0s3 file
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-enp0s3 
    line: "ONBOOT={{ eth_onboot_status }}"
    regexp: "ONBOOT.*"

- name: shut down the enp0s3 
  shell: ifdown enp0s3 

- name: shut down the eth0
  shell: ifdown eth0

- name: start enp0s8
  shell: ifup enp0s8

- name: start enp0s9
  shell: ifup enp0s9

- name: stop firewalld
  shell: systemctl stop firewalld

- name: disable firewalld
  shell: systemctl disable firewalld


# - name: add lines in ifcfg-enp0s3 file
#   lineinfile:
#     path: /etc/sysconfig/network-scripts/ifcfg-enp0s3 
#     line: "ONBOOT={{ eth_onboot_status }}"
#     regexp: "ONBOOT.*"

# - name: shut down the enp0s3 
#   service:
#     name: network
#     state: stopped
#     args: enp0s3 

# - name: shut down the eth0
#   service:
#     name: network
#     state: stopped
#     args: eth0 

# - name: start enp0s8
#   service:
#     name: network
#     state: started
#     args: enp0s8

# - name: start enp0s9
#   service:
#     name: network
#     state: started
#     args: enp0s9

# - name: stop firewalld
#   service:
#     name: firewalld
#     state: stopped

# - name: disable firewalld
#   shell: systemctl disable firewalld

# - name: stop ntpd
#   service:
#     name: ntpd
#     state: stopped

# - name: disable ntpd
#   shell: systemctl disable ntpd

# - name: modify the sysconfig of ntpd
#   lineinfile:
#     path: /etc/sysconfig/ntpd
#     regexp: "OPTIONS.*"
#     line: "OPTIONS=\" -x -u ntp:ntp -p /var/run/ntpd.pid\""

# - name: restart ntpd 
#   service:
#     name: ntpd
#     state: restart





    
  


