# TODO: Add entries for Public, Private, VIRTUAL, and SCAN using Vars
# May not be needed in Charter Env
# Just need to confirm that hostnames do resolve

- name: set the hostname
  hostname: name="{{ inventory_hostname }}"

#*******************************************
# THE BELOW TO BE UNCOMMENTED WHEN WE GET THE LAB ENVIRONMENT WITH ALL THE IP'S REQUIRED
#*******************************************

# - name: ensure the hostname entry exist in /etc/hosts
#   lineinfile:
#     path: /etc/hosts
#     regexp: "^{{ ansible_host }}"
#     line: "{{ ansible_host }} {{ inventory_hostname }}"

# - name: add the hostname and public ip's in /etc/hosts
#   lineinfile:
#     path: /etc/hosts
#     line: "{{ hostname_entries.public_ip }} {{ hostname_entries.public_ip_hostnames | join(' ') }}"

# - name: add the hostname and private ip's in /etc/hosts
#   lineinfile:
#     path: /etc/hosts
#     line: "{{ hostname_entries.private_ip }} {{ hostname_entries.private_ip_hostnames | join(' ') }}"

# - name: add the hostname and private ip's in /etc/hosts
#   lineinfile:
#     path: /etc/hosts
#     line: "{{ item.scan_ip }} {{ item.scan_hostnames | join(' ') }}"
#     state: present
#   with_items:
#     - "{{ hostname_entries.listners }}"

# - name: add lines in resolv.conf file
#   lineinfile:
#     path: /etc/resolv.conf
#     line: "search localdomain"
    
# - name: add lines in resolv.conf file
#   lineinfile:
#     path: /etc/resolv.conf
#     line: "nameserver {{ resolv_ip }}"
#     regexp: "nameserver.*"

#--------------------------------------------