---

- name: set the hostname
  hostname: 
    name: "{{ inventory_hostname }}"

- include: usergroups.yml

- name: create the oracle installation path
  file:
    mode: 0755
    path: "{{ oracle_base }}"
    state: directory
    group: "{{ oracle_group[0].name }}"
    owner: "{{ oracle_user[0].name }}"

- include: packages.yml

# Unsure if we will need this
- include: ora_best_practices.yml

- name: set selinux
  selinux:
    policy: targeted
    state: "{{ selinux_mode }}"

#*******************************************
# THE BELOW TO BE UNCOMMENTED WHEN WE GET THE LAB ENVIRONMENT WITH ALL THE IP'S REQUIRED
#*******************************************

#- include: ntpd_config.yml

#--------------------------------------------

- name: check whether swap space exisits (for cloud instances)
  shell: free  | awk ' $1 == "Swap:" {print $2}'
  register: swapsize

- debug: var=swapsize.stdout

- name: create swap file (for cloud instances)
  include: swap_check.yml
  when: swapsize.stdout | int < 200000

- name: make the NoZeroConf in /etc/sysconfig/network to yes
  lineinfile:
    path: /etc/sysconfig/network
    line: 'NOZEROCONF=yes'

- import_tasks: Charter_checks.yml