---
- name: create tmp dir to store post valdation sql files
  file:
    group: "{{ oracle_group }}"
    owner: "{{ oracle_user }}"
    path: "{{ sql_file_path }}"
    state: directory
    recurse: yes

- name: copy all the sql files that validate db
  copy:
    owner: "{{ oracle_user }}"
    src: "{{ sql_file }}"
    dest: "{{ sql_file_path }}/{{ sql_file }}"
  loop: "{{ sql_files }}"
  loop_control:
    loop_var: sql_file


- name: get oracle_sid
  shell: ps -ef | grep smon | grep {{ oracle_db_name }} | grep -v grep | awk '{ print $8 }'
  register: ps_grep_smon
  changed_when: False

- name: set oracle_sid
  set_fact:
    oracle_sid: "{{ ps_grep_smon.stdout | regex_replace('asm_smon_(.*)', '\\1') }}"
    
- include_tasks: validations.yml

