---
- name: create tmp dir to store post valdation sql files
  file:
    group: "{{ oracle_group }}"
    owner: "{{ oracle_user }}"
    path: "{{ sql_file_path }}"
    state: directory
    recurse: yes

- name: copy all the sql files that validate db
  copy:
    owner: "{{ oracle_user }}"
    src: "{{ sql_file }}"
    dest: "{{ sql_file_path }}/{{ sql_file }}"
  loop: "{{ sql_files }}"
  loop_control:
    loop_var: sql_file

- include_tasks: validations.yml

