---


- name: set orace_home
  block:
    - name: get oracle_sid
      shell: ps -ef | grep smon | grep {{ oracle_db_name }} | grep -v grep | awk '{ print $8 }'
      register: ps_grep_smon
      changed_when: False

    - name: set oracle_sid
      set_fact:
        oracle_sid: "{{ ps_grep_smon.stdout | regex_replace('ora_smon_(.*)', '\\1') }}"
        
    - name: get db details
      command: grep "^{{ oracle_db_name }}:" /etc/oratab
      ignore_errors: yes
      changed_when: false
      register: db_details

    - name: set oracle_home
      set_fact:
        oracle_home: "{{ db_details.stdout | regex_replace('^[^:]*:([^:]*).*', '\\1') }}"
  when: oracle_context != 'GRID'

- name: create tmp dir 
  file:
    group: "{{ oracle_group }}"
    owner: "{{ oracle_user }}"
    path: "{{ oracle_tmp }}"
    state: directory
    recurse: yes

- name: tasks only if db exists
  block:
    - name: create tmp dir to store post valdation sql files
      file:
        group: "{{ oracle_group }}"
        owner: "{{ oracle_user }}"
        path: "{{ sql_file_path }}"
        state: directory
        recurse: yes

    - name: copy all the sql files that validate db
      copy:
        owner: "{{ oracle_user }}"
        src: "{{ sql_file }}"
        dest: "{{ sql_file_path }}/{{ sql_file }}"
      loop: "{{ sql_files }}"
      loop_control:
        loop_var: sql_file
  when: oracle_home != "" and oracle_context != 'GRID'

- include_tasks: validations.yml

