---
- name: create tmp dir to store post valdation sql files
  file:
    group: "{{ oracle_group }}"
    owner: "{{ oracle_user }}"
    path: "{{ sql_file_path }}"
    state: directory
    recurse: yes

- name: copy the manage profile sql file to the instance
  copy:
    owner: "{{ oracle_user }}"
    src: manage_profile.sql
    dest: "{{ sql_file_path }}/manage_profile.sql"

- name: execute manage profile sql file
  become: yes
  become_user: "{{ oracle_user }}"
  environment: "{{ ora_user_env }}"
  shell: sqlplus -S -NOLOGINTIME / as sysdba @{{ sql_file_path }}/manage_profile.sql
  changed_when: false

- name: copy the alter db sql file to the instance
  copy:
    owner: "{{ oracle_user }}"
    src: alter_db.sql
    dest: "{{ sql_file_path }}/alter_db.sql"

- name: execute alter db sql file
  become: yes
  become_user: "{{ oracle_user }}"
  environment: "{{ ora_user_env }}"
  shell: sqlplus -S -NOLOGINTIME / as sysdba @{{ sql_file_path }}/alter_db.sql
  changed_when: false

- name: create a directory
  file:
    group: "{{ oracle_group }}"
    owner: "{{ oracle_user }}"
    path: "{{ install_base }}/admin/{{ oracle_db_name }}/chgctl"
    mode: 'u+rw,g-wr,o-wr'
    state: directory
    recurse: yes

- name: copy sql script to change snapshot interval
  copy:
    owner: "{{ oracle_user }}"
    src: change_snapshot_interval.sql
    dest: "{{ sql_file_path }}/change_snapshot_interval.sql"

- name: execute sql script to change snapshot interval
  become: yes
  become_user: "{{ oracle_user }}"
  environment: "{{ ora_user_env }}"
  shell: sqlplus -S -NOLOGINTIME / as sysdba @{{ sql_file_path }}/change_snapshot_interval.sql
  changed_when: false

- name: copy sql script to modify block tracking
  copy:
    owner: "{{ oracle_user }}"
    src: modify_block_tracking.sql
    dest: "{{ sql_file_path }}/modify_block_tracking.sql"

- name: execute sql script to modify block tracking
  become: yes
  become_user: "{{ oracle_user }}"
  environment: "{{ ora_user_env }}"
  shell: sqlplus -S -NOLOGINTIME / as sysdba @{{ sql_file_path }}/modify_block_tracking.sql
  changed_when: false

- include_tasks: validations.yml

