---

oracle_version: 11.2.0.1

# Oracle Editions avaialble: EE, SEONE, SE
oracle_edition: EE

# installation mode. Avaialable modes are : INSTALL_DB_SWONLY, INSTALL_DB_AND_CONFIG
install_mode: INSTALL_DB_SWONLY

# location for temporary installation files
oracle_tmp: /u01/tmp/{{ oracle_version }}

oracle_base: /u01/app

oracle_db_home: db_1 

oracle_db_name: db

# password for the sysdba
oracle_db_syspass: password

oracle_db_mem: "2048"

# FILE_SYSTEM_STORAGE | ASM_STORAGE
oracle_storage_type: ASM_STORAGE

oracle_asm_syspass: Oracle123

asm_disk_group: DATA

rac_install: false

## TODO: Get standard location where binaries can reliably be found
# For the lab, this path can be mounted using: `mount 10.10.98.164:/export/techlab/ovm /ansible` (nfs-utils & nfs-utils-lib will need to be installed)
oracle_installer_path: "/ansible"

# Whether to start Oracle Enterprise Manager DBconsole
oracle_em: false

