---
- name: Creating no sid entry in ORATAB file
  lineinfile:
    path: /etc/oratab
    line: 'no_sid:{{ oracle_base }}/product/{{ oracle_version }}/{{ oracle_db_home }}:N          # line added by Ansible'

- name: Run Cleanup file job for Database
  command: '{{ oracle_base }}/admin/scripts/cleanup_files.ksh'
  register: cleanup_files

- name: save cleanup_files script stdout
  copy:
    dest: '{{ oracle_tmp }}/cleanup_files.out'
    content: '{{ cleanup_files.stdout }}'

- name: save cleanup_files script stderr
  copy:
    dest: "{{ oracle_tmp }}/cleanup_files.err"
    content: "{{ cleanup_files.stderr | default('') }}"

- name: Set up Directory in ORACLE_ADMIN
  file:
    path: ‘{{ oracle_base }}/admin/chgctl’
    state: directory

- name: Copy the "postprovstalone.sql" to server
  copy: 
    src: ../files/postprovstalone.sql
    dest: "{{ oracle_tmp }}"

#need to update with valid username and password
- name: run postprovstalone.sql script
  become_user: '{{ oracle_user }}'
  environment: "{{ ora_user_env }}"
  command: "sqlplus sys/{{ oracle_db_syspass }} as sysdba @{{ oracle_tmp }}/postprovstalone.sql"
 
