---
- name: Copy the "setup_audit_purge.sql" to server
  copy: 
    src: setup_audit_purge.sql
    dest: "{{ oracle_tmp }}"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    mode: 0755

- name: run setup_audit_purge.sql script
  become: yes
  become_user: '{{ oracle_user }}'
  environment: "{{ ora_user_env }}"
  command: "sqlplus / as sysdba @{{ oracle_tmp }}/setup_audit_purge.sql"
  register: setup_audit_purge

- name: Copy the "Password_Verification_function.sql" to server
  copy: 
    src: Password_Verification_function.sql
    dest: "{{ oracle_tmp }}"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    mode: 0755

- name: run Password_Verification_function.sql script
  become: yes
  become_user: '{{ oracle_user }}'
  environment: "{{ ora_user_env }}"
  command: "sqlplus / as sysdba @{{ oracle_tmp }}/Password_Verification_function.sql"
  register: Password_Verification_function.sql

- name: Copy the "postprovstalone.sql" to server
  copy: 
    src: postprovstalone.sql
    dest: "{{ oracle_tmp }}"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    mode: 0755

- name: run postprovstalone.sql script
  become: yes
  become_user: '{{ oracle_user }}'
  environment: "{{ ora_user_env }}"
  command: "sqlplus / as sysdba @{{ oracle_tmp }}/postprovstalone.sql"
  register: postprovstalone

- name: save postprovstalone script stdout
  copy:
    dest: '{{ oracle_tmp }}/postprovstalone.out'
    content: '{{ postprovstalone.stdout }}'
  changed_when: False

- name: save postprovstalone script stderr
  copy:
    dest: "{{ oracle_tmp }}/postprovstalone.err"
    content: "{{ postprovstalone.stderr | default('') }}"
  changed_when: False
  when: postprovstalone.stderr_lines | length > 0