---
- debug:
    var: ora_user_env

- name: run setup_audit_purge.sql script
  become: yes
  become_user: '{{ oracle_user }}'
  environment: "{{ ora_user_env }}"
  command: "sqlplus / as sysdba @{{ oracle_base }}/admin/scripts/setup_audit_purge.sql"
  register: setup_audit_purge_result
  failed_when: '"ORA-" in setup_audit_purge_result.stdout'

- name: Copy the "Password_Verification_function.sql" to server
  copy: 
    src: Password_Verification_function.sql
    dest: "{{ oracle_base }}/admin/scripts"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    mode: 0755

- name: run Password_Verification_function.sql script
  become: yes
  become_user: '{{ oracle_user }}'
  environment: "{{ ora_user_env }}"
  command: "sqlplus / as sysdba @{{ oracle_base }}/admin/scripts/Password_Verification_function.sql"
  register: Password_Verification_function_result
  failed_when: '"ORA-" in Password_Verification_function_result.stdout'

- name: Copy the "postprovision.sql" to server
  copy: 
    src: postprovision.sql
    dest: "{{ oracle_base }}/admin/scripts"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    mode: 0755

- name: run postprovision.sql script
  become: yes
  become_user: '{{ oracle_user }}'
  environment: "{{ ora_user_env }}"
  command: "sqlplus / as sysdba @{{ oracle_base }}/admin/scripts/postprovision.sql"
  register: postprovision
  failed_when: '"ORA-" in postprovision.stdout'

- name: save postprovision script stdout
  copy:
    dest: '{{ oracle_tmp }}/post-provisioning-setup.out'
    content: '{{ postprovision.stdout }}'
  changed_when: False

- name: save postprovision script stderr
  copy:
    dest: "{{ oracle_tmp }}/post-provisioning-setup.err"
    content: "{{ postprovision.stderr | default('') }}"
  changed_when: False
  when: postprovision.stderr_lines | length > 0