---

oracle_tmp: /u01/tmp/postval

golden_gate_check: False

oracle_user: oracle
grid_version: 12.1.0.2
install_base: /u01/app
oracle_version: 12.1.0.2
oracle_db_home: db_1
oracle_db_name: ''
oracle_context: "{% if oracle_db_name == '' -%}grid
                 {%- else -%}database{%- endif %}"

oracle_home: "{% if oracle_context == 'grid' -%}{{ oracle_base }}/{{ grid_version }}/grid_1
              {%- else -%}{{ install_base }}/oracle/product/{{ oracle_version }}/{{ oracle_db_home }}
              {%- endif %}"


oracle_base: "{{ install_base }}/oracle"
oracle_group: oinstall
sql_file_path: "{{ oracle_tmp }}"

ora_user_env:
  ORACLE_BASE: "{{ oracle_base }}"
  ORACLE_SID: "{{ oracle_sid | default('') }}"
  ORACLE_UNQNAME: "{{ oracle_db_name | default('') }}"
  ORACLE_HOME: "{{ oracle_home }}"
  NLS_LANG: "American_America.UTF8"
  PATH: "{{ oracle_home }}/bin:{{ ansible_env.PATH }}"
  TMP: "/u01/app/oracle"
  TMPDIR: "/u01/app/oracle"
sql_files:
  - verify_dba_directories.sql
  - verify_tablespace.sql
  - verify_alter_profile.sql
  - verify_block_tracking.sql
  - verify_created_profile.sql
  - verify_db_files.sql
  - verify_parallel_force.sql
  - verify_recyclebin_status.sql
  - verify_snapshot_interval.sql
  - verify_redo_logs.sql

oracle_installer_path: https://vm0pnyumxxw0001.twcable.com/yum/source/ORACLE_DB

# vars to be take care
# oracle_db_home
# oracle_context
