---

oracle_tmp: /u01/tmp/postval
ticket_ref: "45678"
golden_gate_check: False
apex_url: "https://apex-dev.techlab.com:8443/ords/invent2"
oracle_user: oracle
grid_version: 12.1.0.2
install_base: /u01/app
oracle_version: 12.1.0.2
# oracle_db_home: db_1
# oracle_db_name: 'apexstg' # TODO: Temporary for debug
#oracle_context: "{% if oracle_db_name == '' -%}grid
#                 {%- else -%}database{%- endif %}"

oracle_home: "{% if oracle_context == 'grid' -%}{{ oracle_base }}/{{ grid_version }}/grid_1
              {%- else -%}{{ install_base }}/oracle/product/{{ oracle_version }}/{{ oracle_db_home }}
              {%- endif %}"


oracle_base: "{{ install_base }}/oracle"
oracle_group: oinstall
sql_file_path: "{{ oracle_tmp }}"

# ora_user_env:
#   ORACLE_BASE: "{{ oracle_base }}"
#   ORACLE_SID: "{{ oracle_db_name }}"
#   ORACLE_UNQNAME: "{{ oracle_db_name | default('') }}"
#   ORACLE_HOME: "{{ oracle_home }}"
#   NLS_LANG: "American_America.UTF8"
#   PATH: "{{ oracle_home }}/bin:{{ ansible_env.PATH }}"
#   TMP: "/u01/app/oracle"
#   TMPDIR: "/u01/app/oracle"

ora_user_env:
  ORACLE_BASE: "{{ oracle_base }}"
  ORACLE_SID: "{{ oracle_db_name }}"
  ORACLE_HOME: "{{ oracle_home }}"
  ORACLE_UNQNAME: "{{ oracle_db_name | default('') }}"
  NLS_LANG: "American_America.UTF8"
  PATH: "{{ oracle_home }}/bin:{{ ansible_env.PATH }}"
  TMP: "/u01/app/oracle"
  TMPDIR: "/u01/app/oracle"

sql_files:
  - verify_dba_directories.sql
  - verify_tablespace.sql
  - verify_alter_profile.sql
  - verify_block_tracking.sql
  - verify_created_profile.sql
  - verify_db_files.sql
  - verify_parallel_force.sql
  - verify_recyclebin_status.sql
  - verify_snapshot_interval.sql
  - verify_redo_logs.sql
  - post_check_audit_purge.sql
  - Password_Verification_function.sql
  - archive_log_mode.sql
  - verify_database_service.sql
  - verify_memory_values.sql

oracle_installer_path: https://vm0pnyumxxw0001.twcable.com/yum/source/ORACLE_DB

# vars to be take care
# oracle_db_home
# oracle_context
