---

- name: Run Opatch Prereqs
  become: yes
  become_user: "{{ oracle_user }}"
  environment: "{{ ora_user_env }}"
  command: "{{ opatch_bin  }} prereq CheckConflictAgainstOHWithDetail -phBaseDir {{ pstage }}/{{ patch_num }}"
  register: opatch_prereq

- name: save opatch prereq stdout
  copy:
    dest: "{{ oracle_tmp }}/opatch_prereq.out"
    content: "{{ opatch_prereq.stdout }}"

- name: save opatch prereq stderr
  copy:
    dest: "{{ oracle_tmp }}/prereq.err"
    content: "{{ opatch_prereq.stderr }}"

- name: Run Opatch
  become: yes
  become_user: "{{ oracle_user }}"
  environment: "{{ ora_user_env }}"
  command: "{{ opatch_bin  }} apply -oh ${{ patch_type }}_HOME -local {{ pstage }}/{{ patch_num }}"
  register: opatch_apply

- name: save opatch apply stdout
  copy:
    dest: "{{ oracle_tmp }}/opatch_apply.out"
    content: "{{ opatch_apply.stdout }}"

- name: save opatch prereq stderr
  copy:
    dest: "{{ oracle_tmp }}/opatch_apply.err"
    content: "{{ opatch_apply.stderr }}"
  
- name: Check Opatch Inventory
  become: yes
  become_user: "{{ oracle_user }}"
  environment: "{{ ora_user_env }}"
  command: "{{ opatch_bin  }} lsinventory"
  register: opatch_lsinv
