---

- name: cleanup cluvfy 2nd stdout
  listen: check cluvfy failures
  replace:
    path: "{{ oracle_tmp }}/cluvfy_2nd_stdout.out"
    regexp: 'FAILED'
    replace: 'failed'
    before: 'Failures were encountered during execution.*'

- name: ignore known cluvfy failures
  listen: check cluvfy failures
  lineinfile:
    path: "{{ oracle_tmp }}/cluvfy_2nd_stdout.out"
    regexp: ".*{{ item }}.*FAILED"
    line: "{{ item }} IGNORED"
  with_items: "{{ known_cluvfy_issues }}"

- name: Any non-ignorable failures?
  listen: check cluvfy failures
  command: "grep FAILED {{ oracle_tmp }}/cluvfy_2nd_stdout.out"
  register: cluvfy_failures
  failed_when: cluvfy_failures.stdout_lines | length > 0
  changed_when: cluvfy_failures.rc != 0
