---

- name: run cluvfy again
  listen: re-run cluvfy
  become: yes
  become_user: "{{ oracle_user }}"
  environment: "{{ ora_user_env }}"
  command: "{{ oracle_tmp }}/cluster_verify/bin/cluvfy stage -pre crsinst -n {{ ansible_hostname }}"
  ignore_errors: yes
  register: cluvfy_results_2

- name: save cluvfy 2nd stdout
  listen: re-run cluvfy
  copy:
    dest: "{{ oracle_tmp }}/cluvfy_2nd_stdout.out"
    content: "{{ cluvfy_results_2.stdout }}"

- name: save cluvfy 2nd stderr
  listen: re-run cluvfy
  copy:
    dest: "{{ oracle_tmp }}/cluvfy_2nd_stderr.err"
    content: "{{ cluvfy_results_2.stderr }}"
  
  
- name: Check for cluvfy failure
  listen: re-run cluvfy
  command: echo RC=$?
  notify: check cluvfy failures
  when: cluvfy_results_2.rc != 0