---

- name: get cluvfy version
  listen: run fixup script
  become: yes
  become_user: "{{ oracle_user }}"
  environment: "{{ ora_user_env }}"
  command: "{{ oracle_tmp }}/cluster_verify/bin/cluvfy -version"
  register: cluvfy_version

- name: check for runfixup.sh
  listen: run fixup script
  find:
    paths: "/tmp/CVU_{{ cluvfy_version.stdout | regex_replace('^(.*) Build.*', '\\1') }}_oracle"
    file_type: file
    patterns: runfixup.sh
    use_regex: no
  register: fixup_script

- name: execute runfixup.sh
  listen: run fixup script
  command: "{{ fixup_script.files[0].path }}"
  ignore_errors: yes
  register: fixup_results
  when: fixup_script.matched == 1

- name: save runfixup.sh stdout
  listen: run fixup script
  copy:
    dest: "{{ oracle_tmp }}/fixup_stdout.out"
    content: "{{ fixup_results.stdout }}"
  when: fixup_results is defined

- name: save runfixup.sh stderr
  listen: run fixup script
  copy:
    dest: "{{ oracle_tmp }}/fixup_stderr.err"
    content: "{{ fixup_results.stderr }}"
  when: fixup_results is defined
